### ISSUE TITLE
Non-voting node with hiigher importances does not get rollback when a fork is resolved.

### ISSUE THREAD

**Issue by Wayonb** [nemtech/catapult-server#108]
repro:
1. setup a chain with 3 nodes(api-node, 2 peers)
2. Api-node have twice the importance of the other nodes.
3. Fork the api node for 2 epoch period.
4. Resolve the fork with the api-node so it rejoins the chain.

Expected the api-node to rollback to the common block.

[deep_rollback_logs.tar.gz](https://github.com/nemtech/catapult-server/files/5527191/deep_rollback_logs.tar.gz)

**Comment by Jaguar0625** [comment]
Fixed in c6f2ffd3a.
