### ISSUE TITLE
Expose nodePublicKey (node.key.pem) in api packet types 0x111, 0x113

### ISSUE THREAD

**Issue by fboucquez** [nemtech/catapult-server#110]
For delegate haversting, clients need to provide the `node.key.pem` public key in the delegate transfer transactions. Atm the public key is not exposed in the server api or rest. 
We are trying to expose that key in rest from the known local `node.key.pem` file but I think it would fit better if the following packet types:
```
/** Node information has been requested by a peer. */
nodeDiscoveryPullPing: 0x111,

/** Node peers had been requested by a peer. */
nodeDiscoveryPullPeers: 0x113,
```

are extended adding the nodePublicKey in the payload. This would allow rest and client to not only know the node public key of the "local" server api but also the node public key of the known peers. 

Then rest could show the node keys like:

/node/info (local)
![image](https://user-images.githubusercontent.com/5390558/99136421-7420dc00-2603-11eb-9517-c5dd0a7315a2.png)

/node/peers (known remotes)

![image](https://user-images.githubusercontent.com/5390558/99136492-d7ab0980-2603-11eb-8407-2ba7027cc561.png)

Note that the current exposed `publicKey` is the main account from CA public key. (Could we rename it to `caPublicKey` to avoid confusion?)

Exposing this public key could be optional, Maybe the node admin doesn't want to make this public key public. Server api could return 00000 public key in the payload (or similar if we have old nodes without this feature on)

**Comment by fboucquez** [comment]
@Jaguar0625 @gimer would this be doable in a future server release? We are adding in /node/info the node public key as workaround to unblock the clients but it would be great if server api provides those.

**Comment by Jaguar0625** [comment]
Node key can be extracted from TLS handshake with server. This handshake is performed when making any connection to the server. REST and/or SDK can certainly initiate and extract this. So, I don’t see the need for this.
