### ISSUE TITLE
Add version to states in mongo collections

### ISSUE THREAD

**Issue by fboucquez** [nemtech/catapult-server#113]
Atm, version value is not stored in the mongo db, not returned via rest or open api and not serialized in catbuffer/sdk.

![image](https://user-images.githubusercontent.com/5390558/99675518-1141a180-2a56-11eb-8c54-566a0c0046f3.png)

Without the version, it seems like it's not going to be possible to do the proofs. 

This task would be to add the version to the mongo db collections than then rest can return in the rest payloads.

**Comment by Jaguar0625** [comment]
Fixed in 8add85f1b.
