### ISSUE TITLE
Account restriction state serialization

### ISSUE THREAD

**Issue by rg911** [nemtech/catapult-server#114]
Account restriction state serialization appends place holder buffer for empty restriction types. 

e.g. When serializing allows incoming address restriction only, below empty restriction types are also needed (appended) to the restriction state. Otherwise, the state hash won't match the merkle leaf value. 

```
| 0280 | 0000000000000000 | mosaic id (block)
| 01C0 | 0000000000000000 | address (block, outgoing)
| 04C0 | 0000000000000000 | transaction type (block, outgoing)
```

The proposed change would be to remove empty restriction types placeholder, only serialize the actual restriction state.

**Comment by Jaguar0625** [comment]
Fixed in 8a73c6515.
