### ISSUE TITLE
State version is in meta and not in main entry like other documents

### ISSUE THREAD

**Issue by fboucquez** [nemtech/catapult-server#115]
Hi @jaguar0625, thank you for adding the version to the server, catbuffer, and mongo. I have a question about the mongo location. It seems like the version is stored in the "meta" column and not in the main entry of the document. 

https://github.com/nemtech/catapult-server/commit/8add85f1bd7a2ab5afd14191a42609e9513e1914

Mosaic as example:

![image](https://user-images.githubusercontent.com/5390558/100303086-7d526700-2f7a-11eb-94fd-f8d119aa4a4d.png)

I don't think the version is a "meta" value. It's part of the serialized payload and it's required for the state proof like any other value. Also, block and transaction versions are stored in the main entry of the document (not in meta). Should we have the version field on the main entry of the document?

![image](https://user-images.githubusercontent.com/5390558/100303145-a70b8e00-2f7a-11eb-958f-30e7a8766340.png)

![image](https://user-images.githubusercontent.com/5390558/100303151-aa067e80-2f7a-11eb-9f10-4ad5c9902820.png)

I could move on rest the version field from meta to the main object when mapping from the database, but it's not that trivial due to the way rest is coded and I would prefer to keep it consistent at db level.

**Comment by gimer** [comment]
in transactions / block, etc this is part of the model itself... in case of state this is part of meta (would wait for comment from @Jaguar0625 though)

**Comment by fboucquez** [comment]
Version would be the only meta value in most states. IMHO I think it's not a meta, it is part of the serialized state like any other value.

**Comment by Jaguar0625** [comment]
Fixed in 3533c2b7e.
