### ISSUE TITLE
Testnet stalled on the importance block

### ISSUE THREAD

**Issue by Wayonb** [nemtech/catapult-server#118]
the stall was caused by the interaction (and order) of two observers: 

1. HighValueAccount => reanalyzes voter and harvester eligibility
2. ExpiredHashLockInfo[*] => credits harvester on expiry of hash lock
the first bug is that expired hash lock credits are ignored until the next block for purposes of voter+harvester eligibility checks. [state hashes are correct because the most recent state is used when calculating state hash.]
the second bug is that the harvester added an explicit call to updateHighValueAccounts (which is what is called by the observer) AFTER all block notifications.

**Comment by Jaguar0625** [comment]
Fixed in 0a2498cc3.
