### ISSUE TITLE
Improve how deep rollback restore account state importance.

### ISSUE THREAD

**Issue by Wayonb** [nemtech/catapult-server#119]
there's a problem with how we do deep rollback for account state. in certain cases, we'll corrupt the importance files.
1. single chain part causes rollback of X, Y, Z importance blocks
2. recalculate importances at X, Y => THIS OVERWRITES DISK FILES
3. reject chain part due to invalid tx/block
importance files (and index) files reflect (incomplete) processing of chain block.
so disk files important files reflect X', Y'
and last importance height (used for optimizations) is H(Y)

**Comment by Jaguar0625** [comment]
Fixed in 3f5307ec8.
