### ISSUE TITLE
Mongo migration tool

### ISSUE THREAD

**Issue by fboucquez** [nemtech/catapult-server#122]
Currently, if a new version of the server changes the mongo collections, existing data is not being migrated to the new format. If this happens, the node admin would need to reset the Mongo DB (and RocksDB) and sync from scratch. This process could take hours/days in production.  

This task is to create a tool that upgrades a Mongo DB doing the migrations from one version to another.  

For example, a migration tool from 0.10.0.3 to 0.10.0.4 that:

1. Adds version 1 to states
2. Renames "active" for "latest" in namespaces.
3. Truncates the voting keys from 48 to 32

Would have been useful and much faster than full resync.

Note that although the owner of the Mongo DB is Server, this tool doesn't have to be done in C++ necessarily. 

https://www.npmjs.com/package/migrate-mongo

**Comment by Jaguar0625** [comment]
Closing because we have no migration needs prior to mainnet launch. We can revisit if and when there is a need for a mongo migration script.
