### ISSUE TITLE
Local Mongo sync tool

### ISSUE THREAD

**Issue by fboucquez** [nemtech/catapult-server#123]
Atm, if the mongo db is not up to date with the RocksDB, the recovery and broker processes fail with a :

api-broker      | 2020-12-10 12:28:51.601624 0x00007faae2bd9400: <error> (local::HostUtils.h@44) Throwing exception: cannot save block with height 2 when storage height is 0

The node admin would need to do a full resync to recover, full sync could take several hours or days.

I would like to have a tool that puts a MongoDB up to date locally by inserting the missing data from RocksDB. The 2 main use cases are:

- Resilience, if for any reason, a mongo db gets old for a few heights, local sync would recover the node without a full resync.
- Fast Sync, if NGL provides a RocksDB zip for a network, the tool could recreate the mongo db locally. One alternative would be downloading a ZIP with both RockDB and MongoDB if a full local sync is slower/more expensive than downloading a dual db zip.

https://github.com/nemtech/symbol-bootstrap/issues/70 

Local full sync could take a long time to run, but much faster than full remote sync.

**Comment by Jaguar0625** [comment]
> if the mongo db is not up to date with the RocksDB

Can you explain what steps you took to end up in this state?

**Comment by fboucquez** [comment]
Hi @Jaguar0625 , sorry for the late response. The question when under my radar. 

I was messing up with the recovery solution I've I noticed that the mongo when bad just a few heights older. That required a full resync just for a couple of missing blocks. 

Another use case is when you want to fast sync when you only have a rockdb. So on boot time, server or a tool can move mongo from 0 to rockdb height.  Atm a dual node fast sync solution will required upgrading and downloading 2 files, rockdb and mongodb zip backups (and both must be in sync with each other, in mongo is off, the whole backup won't work)

**Comment by Jaguar0625** [comment]
> I noticed that the mongo when bad just a few heights older

You mean the broker crashed and recovery wasn't run?

> Another use case is when you want to fast sync when you only have a rockdb

I'm not sure if this is a valid usecase. If you have all blocks locally but an empty rocksdb and mongo you should be able to use recovery tool to populate databases:

1. copy all blocks from peer node to a new machine
1. [on new machine] prepare resources
1. run recovery
1. boot

**Comment by Jaguar0625** [comment]
Closing per @Wayonb since this shouldn't normally happen:

> I noticed that the mongo when bad just a few heights older
