### ISSUE TITLE
Infinite loop in the compare chains logic

### ISSUE THREAD

**Issue by Wayonb** [nemtech/catapult-server#126]
(chain::CompareChains.cpp@120) comparing chain scores: 427499091779639169 (local) vs 432073415811740421 (remote) 
 (chain::CompareChains.cpp@146) comparing hashes with local height 4261, starting height 1, max hashes 1210 
 (chain::CompareChains.cpp@146) comparing hashes with local height 4261, starting height 2131, max hashes 1210 
 (chain::CompareChains.cpp@146) comparing hashes with local height 4261, starting height 3196, max hashes 1210 
 (chain::CompareChains.cpp@146) comparing hashes with local height 4261, starting height 4260, max hashes 1210 
 (chain::CompareChains.cpp@146) comparing hashes with local height 4261, starting height 3195, max hashes 1210 
 (chain::CompareChains.cpp@146) comparing hashes with local height 4261, starting height 4260, max hashes 1210 
 (chain::CompareChains.cpp@146) comparing hashes with local height 4261, starting height 3195, max hashes 1210 
 (chain::CompareChains.cpp@146) comparing hashes with local height 4261, starting height 4260, max hashes 1210 
 (chain::CompareChains.cpp@146) comparing hashes with local height 4261, starting height 3195, max hashes 1210 
 (chain::CompareChains.cpp@146) comparing hashes with local height 4261, starting height 4260, max hashes 1210 
 (chain::CompareChains.cpp@146) comparing hashes with local height 4261, starting height 3195, max hashes 1210 
 (chain::CompareChains.cpp@146) comparing hashes with local height 4261, starting height 4260, max hashes 1210 
 (chain::CompareChains.cpp@146) comparing hashes with local height 4261, starting height 3195, max hashes 1210

**Comment by Jaguar0625** [comment]
Fixed in 7565a9bc2.
