### ISSUE TITLE
Example Dockerfile

### ISSUE THREAD

**Issue by mliang-circle** [nemtech/catapult-server#127]
Hi! Is there possible providing example Dockerfile for building symbol-server?

**Comment by CrackTheCode016** [comment]
I have a basic Dockerfile working with conan here: https://github.com/IoDLT/iodlt-symbol-server-docker/blob/main/Dockerfile

**Comment by mliang-circle** [comment]
Thanks!

**Comment by mliang-circle** [comment]
Hi, I tried the dockerfile with `main` branch, but the build failed with error
```
#21 307.2 [313/918] Linking CXX executable bin/catapult.broker
#21 307.2 FAILED: bin/catapult.broker 
...
...
...
#21 307.2 collect2: error: ld returned 1 exit status
#21 307.2 [314/918] Building CXX object sdk/src/CMakeFiles/catapult.sdk.dir/builders/AddressAliasBuilder.cpp.o
#21 308.8 [315/918] Building CXX object sdk/src/CMakeFiles/catapult.sdk.dir/builders/AggregateTransactionBuilder.cpp.o
#21 309.2 [316/918] Building CXX object sdk/src/CMakeFiles/catapult.sdk.dir/builders/HashLockBuilder.cpp.o
#21 309.2 ninja: build stopped: subcommand failed.
------
failed to solve with frontend dockerfile.v0: failed to build LLB: executor failed running [/bin/sh -c ninja publish && ninja -j4]: runc did not terminate sucessfully
```

any suggestion how to fix?

**Comment by mliang-circle** [comment]
`v0.10.0.4` failed on build `RUN conan install /home/server --build missing`
with error
```
#19 7.490 ERROR: boost/1.74.0: Invalid configuration: chrono requires ['system']: system is disabled
------
failed to solve with frontend dockerfile.v0: failed to build LLB: executor failed running [/bin/sh -c conan install /home/server --build missing]: runc did not terminate sucessfully
```

**Comment by gimer** [comment]
@mliang-circle we could provide *some* dockerfile, but it would be good to know first, what is your intent.

The problem that we have is that docker as is distributed in various distribution, does not allow builds with sources (and object files) externally mounted.
So instead we're building in one image and copy all required executables + plugins + extensions and dependencies into separate image.

**Comment by rg911** [comment]
```
#19 7.490 ERROR: boost/1.74.0: Invalid configuration: chrono requires ['system']: system is disabled
```
I think @mliang-circle is trying to build off test/v3 branch which hasn't got [this](https://github.com/nemtech/catapult-server/commit/d501ee5ecd52afbddbe5930259317cdc8cc67f63). A workaround is to manually update the conanbuild.txt file see https://github.com/nemtech/catapult-server/issues/124

**Comment by Jaguar0625** [comment]
closing as builds against main are working now and docs have been updated
