### ISSUE TITLE
error while loading shared libraries

### ISSUE THREAD

**Issue by mliang-circle** [nemtech/catapult-server#128]
Hi, I have built symbol-server without CONAN following https://github.com/nemtech/catapult-server/blob/main/docs/BUILD-manual.md.

But when I run the scripts, keeps getting `error while loading shared libraries`. Sometimes this can be fixed by setting LD_LIBRARY_PATH include path with *.so file. But I don't expect this to be a long term fix. Any suggestion?

**Comment by gimer** [comment]
this actually *is* long term solution, for production-ready deployments, you should be using LD_LIBRARY_PATH and point it to *proper* dependencies.

The only alternative is setting rpath or runpath, but this is discouraged by debian (among others)
https://wiki.debian.org/RpathIssue
> Currently, the only generally accepted use of this feature in Debian is to add non-standard library path (like /usr/lib/<package>) to libraries that are only intended to be used by the executables or other libraries within the same source package.

(that obviously is not the case in case of external dependecies)

For "dev" builds, we could add some additional option to set rpath/runpath
(we actually were doing this earlier by default, right now we only do that for macos conan builds)

**Comment by gimer** [comment]
closing the issue, if you need any more help re-open or create new
