### ISSUE TITLE
Enhance cross chain swap functionality

### ISSUE THREAD

**Issue by kaiyzen** [nemtech/catapult-server#13]
Currently catapult supports Op_Keccak_256 and Op_Sha3_512, its desired to add some more algorithms to increase the number of compatible ledgers that can be interacted with.

Other ones tbd such as also looking into allowing for interactivity with layer 2 solutions such as lightning

**Comment by Jaguar0625** [comment]
catapult should support all of following lock hash algorithms for secret locks:
1. Op_Sha3_512: Input is hashed using Sha-3-512. (Catapult native)
2. Op_Keccak_256: input is hashed using Keccak-256. (ETH compat)
3. Op_Hash_160: input is hashed twice: first with SHA-256 and then with RIPEMD-160. (BTC compat)
4. Op_Hash_256: input is hashed twice with SHA-256. (BTC compat)

**Comment by Jaguar0625** [comment]
decided to change catapult native to sha2 256 instead of sha3 512

**Comment by Jaguar0625** [comment]
8467be1485db44d60a9704ddf2eeab9050273911
