### ISSUE TITLE
Updated config scripts https://github.com/IoDLT/cat-config-scripts

### ISSUE THREAD

**Issue by mliang-circle** [nemtech/catapult-server#131]
Hi!

I am looking for help start node join test node without symbol-bootstrap.

I have successfully built symbol-server from source code, but have a hard time following the docs https://github.com/nemtech/catapult-server/blob/main/docs/RUNNETWORKLIN.md and https://github.com/nemtech/catapult-server/blob/main/docs/RUNPEERLIN.md. 

I also found this https://github.com/IoDLT/cat-config-scripts in https://forum.nem.io/t/nem-catapult-developer-resources/23011. I would like to know which version cat-config-scripts support.

**Comment by Jaguar0625** [comment]
Please let us know what is unclear about the docs. 

I am unsure of the status of cat-config-scripts at this time, but believe bootstrap is intended to replace them. @CrackTheCode016 ?

**Comment by segfaultxavi** [comment]
Hi @mliang-circle, there are a couple of pull requests pending review to update the docs:
https://github.com/nemtech/catapult-server/pull/138
https://github.com/nemtech/catapult-server/pull/139

Could you check them out and tell us if you still have issues following them?

**Comment by Jaguar0625** [comment]
closing as documentation PRs have been merged
