### ISSUE TITLE
Implement new fee handling that can be more dynamic

### ISSUE THREAD

**Issue by kaiyzen** [nemtech/catapult-server#14]
It is desired to improve on the nis1 fee handling, making things more dynamic and taking into account things such as size and complexity of the transaction.

**Comment by Jaguar0625** [comment]
1. NEM Blocks will be extended to include a new uint32 “fee multiplier” field. All values are acceptable, including zero.
2. Transaction fee field will be changed to represent the maximum fee paid for confirmation.
3. Fees will be based entirely on transaction size. Within a block, a transaction’s effective fee will be transaction::size * block::fee_multiplier. For unconfirmed transactions, max_fee will be assumed.
4. Harvesting nodes will be able to set the minimum fee multiplier they will put into blocks they harvest.
5. Harvesting nodes will be able to pick their transaction inclusion strategy: prefer-oldest (preferred for high TPS), minimize-fees (for benevolent nodes), maximize-fees (for most nodes)
Please advise if there are any concerns with this approach. Thanks!

*note: fees are dynamic and determined by market, so we don’t envision any future changes to this model in foreseeable future*

**Comment by Jaguar0625** [comment]
8467be1485db44d60a9704ddf2eeab9050273911
