### ISSUE TITLE
Implement new harvesting capabilities

### ISSUE THREAD

**Issue by kaiyzen** [nemtech/catapult-server#15]
This feature is to track the implementation of new harvesting capabilities to be added.  The goal is to allow for deployed networks to create a nice incentive structure for supporters of the network to run full nodes and having the ability to get compensated for doing so.

**Comment by hxiewally** [comment]
Is there any more possible detail here on additional and modified incentives for new harvesting? I'm writing a piece previewing Dragon for NF, so any additional info here would be helpful. Thanks.

**Comment by BloodyRookie** [comment]
The following change is already implemented in the current release:
A node owner that is letting other accounts harvest is getting a certain percentage of the fees that are harvested. The percentage is the same for all nodes in the network and can be found in config-network.properties. Name is "harvestBeneficiaryPercentage". The node ower can specify the account that is credited (file config-harvesting.properties, field "beneficiary")

**Comment by Vektrat** [comment]
is this information exposed anywhere? (`beneficiary`)

@dgarcia360 suggested that REST offers an endpoint regarding this, and right now it cannot access this information if it's just in a config file ^^

> Endpoint to get the node beneficiary if set: Useful to determine where I should delegate my importance

**Comment by BloodyRookie** [comment]
i don't think we will provide node specific information like beneficiary in the near future.
If you have the feeling that it is very important, please open a separate issue.
