### ISSUE TITLE
totalFee < effectiveFee

### ISSUE THREAD

**Issue by xembook** [nemtech/catapult-server#151]
about block height:65622

this block's totalFee is  2,243.096096 XYM
```
(await blockRepo.getBlockByHeight(65622).toPromise()).totalFee
```

and this block has only 1 aggregate transaction. 
(hash:94DCBD12E84C92AEC6E21AB565944C6FFC13A31A14076BF59388202A7DC13636)

this tx's effectiveFee is 6,538.063392 XYM
```
await txRepo.getTransactionEffectiveFee("94DCBD12E84C92AEC6E21AB565944C6FFC13A31A14076BF59388202A7DC13636").toPromise()
```
and `feeMultiplier * tx.size`  is same value

I don't know why totalFee < effectiveFee

**Comment by Jaguar0625** [comment]
Fixed in f7a61d343.
