### ISSUE TITLE
Make --input parameter optional in catapult.tools.addressgen

### ISSUE THREAD

**Issue by segfaultxavi** [nemtech/catapult-server#153]
The new addressgen tool has an option to search for addresses containing a specific input string, which is pretty cool.
But I don't think it should be a mandatory parameter. Currently, if not used, no address is generated.
As a workaround, you can use `--input N` because all addresses will contain an N, but this is cumbersome, and does not look very good in the guides.

**Comment by Jaguar0625** [comment]
Fixed in 179c1d4e9 .
