### ISSUE TITLE
Misleading error returned when StartEpoch=0 in voting key link

### ISSUE THREAD

**Issue by segfaultxavi** [nemtech/catapult-server#170]
From this Slack thread:
https://nemgroup-workspace.slack.com/archives/C015AEQ9ZL2/p1616153305123400

When trying to link a voting key with StartEpoch=0 the returned error is `Failure_Core_Link_Already_Exists` which does not help much when trying to find the cause of the error.

**Comment by Jaguar0625** [comment]
Fixed in 24afbfc26.
