### ISSUE TITLE
harvestars.dat not fully recovered after re-sync

### ISSUE THREAD

**Issue by fboucquez** [nemtech/catapult-server#173]
It seems like harvesters.dat file is not fully recovered after a data reset/resync. 

Case:

1) I've created a testnet node locally and added 2 delegate harvesters:

Testnet node main: http://explorer.testnet.symboldev.network/accounts/TCY32Q4HCVRBKELPKJ3JTLXHAKZDZYFLMP5MQ6Y
Harvester 1: http://explorer.testnet.symboldev.network/accounts/TDTV2MRQI2ZEG7MDY6PB3KTUUO7XXXZGQUTO4XY
Harvester 2: http://explorer.testnet.symboldev.network/accounts/TD4AV6X4JGSJTDHMV6IARAEKFG7SYHC6DJVQBSI 

Both appear in the http://localhost:3000/node/unlockedaccount endpoint and harvesters.dat. I have a backup of this file. 

I have sent 1 delegate transfer transaction for Harvester 1 and 3 delegate transfer transactions for Harvester 2. You can see the transactions for each account in the explorer links. I use the new desktop wallet to enable delegate harvesting for these accounts.

2) Stop the server, remove mongo and data folders, and restart (symbol-bootstrap start --resetData).  

Note that the keys and configuration are the same. 

Once synced, only the harvester 2 has been recovered and added back to the harvesters.dat and http://localhost:3000/node/unlockedaccount.

Harvester 1 seems missing.

Note that harvester 1 only has sent the delegate transfer once. Harverster 2 several times and it does recover after resync. 

I've seen similar behavior in my own mainnet server, I've lost delegate harvesters when I did a resync. 

I think there are community members having the same issue, I need to confirm. One could be https://nem2.slack.com/archives/C9YKR0EUX/p1618854094288800

I can provide the custom preset file with this testnet node configuration and keys. I believe you will be able to recreate the node and this issue locally. 

I'm not sure this is an issue, but it does smell like one. If this is not an issue, is it possible to regenerate the harvesters.dat file using the chain information with a command? Should we need to keep backup of the harversters.dat when doing a resync?

**Comment by Jaguar0625** [comment]
Did you change node keys inbetween resync?

**Comment by fboucquez** [comment]
No, I didn't change the keys, same certificates and configuration between resyncs

**Comment by Jaguar0625** [comment]
Resolved in c46579897.

**Comment by fboucquez** [comment]
To recovered lost harvesters, is restarting the (new) server enough or should we resync?

**Comment by Jaguar0625** [comment]
you need to resync
