### ISSUE TITLE
Enhance harvesting configuration

### ISSUE THREAD

**Issue by kaiyzen** [nemtech/catapult-server#21]
Goal of this feature update is to all a server/network to configure and define whats its "base harvesting" asset is vs being hard wired to "nem:xem" per se.  This functionality will allow the setting of the default asset to be leveraged for fees/harvesting and any other block reward enhancements that might be introduced

**Comment by Jaguar0625** [comment]
network owner will be able to configure separately:
1. currencyMosaicId - mosaic id used as primary chain currency
2. harvestingMosaicId - mosaic id used to provide harvesting ability

**Comment by Jaguar0625** [comment]
8467be1485db44d60a9704ddf2eeab9050273911
