### ISSUE TITLE
Data lost after crash

### ISSUE THREAD

**Issue by jabo38** [nemtech/catapult-server#22]
Problem forwarded to me by Eliptica:
If you have a internal NIS running on a virtual machine and it is turned off by an electrical failure, in
most cases it is impossible to recover the information at a certain block height. The nemesis block must
be created again and synchronized with another existing node to reestablish its operation and recover
the information. If there is no other node, all information is lost.

**Comment by gimer** [comment]
@jabo38 why is this reported in catapult-server though?

**Comment by gimer** [comment]
we are aware of it.

**Comment by jabo38** [comment]
sorry, I posted in the wrong place.

**Comment by Jaguar0625** [comment]
Fixed in dragon (95e0c6a).
