### ISSUE TITLE
build is crashed

### ISSUE THREAD

**Issue by UmSergDev** [nemtech/catapult-server#3]
Good day community,
how to solve this compilation error
Tnx

iMac-Sergey:_build sergeyumarov$ cmake -DCMAKE_BUILD_TYPE=RelWithDebugInfo ..
-- The C compiler identification is AppleClang 9.1.0.9020039
-- The CXX compiler identification is AppleClang 9.1.0.9020039
-- Check for working C compiler: /Library/Developer/CommandLineTools/usr/bin/cc
-- Check for working C compiler: /Library/Developer/CommandLineTools/usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /Library/Developer/CommandLineTools/usr/bin/c++
-- Check for working CXX compiler: /Library/Developer/CommandLineTools/usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
fatal: not a git repository (or any of the parent directories): .git
fatal: not a git repository (or any of the parent directories): .git
-- CATAPULT_VERSION_DESCRIPTION:  []
-- CMAKE_CXX_COMPILER_ID: AppleClang
-- CMAKE_CXX_FLAGS:  		-std=c++11 -stdlib=libc++ 		-Weverything 		-Werror 	-Wno-c++98-compat 		-Wno-c++98-compat-pedantic 		-Wno-disabled-macro-expansion 		-Wno-padded 		-Wno-switch-enum 		-Wno-weak-vtables -fvisibility=hidden
-- BOOST_ROOT: 
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - found
-- Found Threads: TRUE  
-- Boost version: 1.67.0
-- Found the following Boost libraries:
--   atomic
--   system
--   date_time
--   regex
--   timer
--   chrono
--   log
--   thread
--   filesystem
--   program_options
--   log_setup
--- locating rocksdb dependencies ---
rocksdb   lib: /usr/local/lib/librocksdb.dylib
rocksdb   inc: /usr/local/include
-- Found GTest: /usr/local/lib/libgtest.a  
--- locating mongo dependencies ---
  mongo c    lib: /usr/local/lib/libmongoc-1.0.dylib
   bson c    lib: /usr/local/lib/libbson-1.0.dylib
  mongo cxx dirs: MONGOCXX_LIB-NOTFOUND /usr/local/include/mongocxx/v_noabi;/usr/local/include/bsoncxx/v_noabi  /usr/local/lib/libmongocxx.dylib;/usr/local/lib/libbsoncxx.dylib
   bson cxx dirs: BSONCXX_LIB-NOTFOUND /usr/local/include/bsoncxx/v_noabi  /usr/local/lib/libbsoncxx.dylib
--- locating zeromq dependencies ---
  zeromq dirs: /usr/local/include
   cppmq dirs: /usr/local/include
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
BSONCXX_LIB
    linked by target "extension.mongo" in directory /Users/sergeyumarov/catapult-server-master/extensions/mongo
    linked by target "catapult.mongo.plugins.aggregate" in directory /Users/sergeyumarov/catapult-server-master/extensions/mongo/plugins/aggregate/src
    linked by target "tests.catapult.mongo.plugins.aggregate" in directory /Users/sergeyumarov/catapult-server-master/extensions/mongo/plugins/aggregate/tests
    linked by target "catapult.mongo.plugins.lock.deps" in directory /Users/sergeyumarov/catapult-server-master/extensions/mongo/plugins/lock/src
    linked by target "tests.catapult.mongo.plugins.lock" in directory /Users/sergeyumarov/catapult-server-master/extensions/mongo/plugins/lock/tests
    linked by target "tests.catapult.int.mongo.plugins.lock" in directory /Users/sergeyumarov/catapult-server-master/extensions/mongo/plugins/lock/tests/int
    linked by target "tests.catapult.test.mongo.plugins.lock" in directory /Users/sergeyumarov/catapult-server-master/extensions/mongo/plugins/lock/tests/test
    linked by target "catapult.mongo.plugins.multisig.deps" in directory /Users/sergeyumarov/catapult-server-master/extensions/mongo/plugins/multisig/src
    linked by target "tests.catapult.mongo.plugins.multisig" in directory /Users/sergeyumarov/catapult-server-master/extensions/mongo/plugins/multisig/tests
    linked by target "tests.catapult.int.mongo.plugins.multisig" in directory /Users/sergeyumarov/catapult-server-master/extensions/mongo/plugins/multisig/tests/int
    linked by target "tests.catapult.test.mongo.plugins.multisig" in directory /Users/sergeyumarov/catapult-server-master/extensions/mongo/plugins/multisig/tests/test
    linked by target "catapult.mongo.plugins.namespace.deps" in directory /Users/sergeyumarov/catapult-server-master/extensions/mongo/plugins/namespace/src
    linked by target "tests.catapult.mongo.plugins.namespace" in directory /Users/sergeyumarov/catapult-server-master/extensions/mongo/plugins/namespace/tests
    linked by target "tests.catapult.int.mongo.plugins.namespace" in directory /Users/sergeyumarov/catapult-server-master/extensions/mongo/plugins/namespace/tests/int
    linked by target "tests.catapult.test.mongo.plugins.namespace" in directory /Users/sergeyumarov/catapult-server-master/extensions/mongo/plugins/namespace/tests/test
    linked by target "catapult.mongo.plugins.transfer" in directory /Users/sergeyumarov/catapult-server-master/extensions/mongo/plugins/transfer/src
    linked by target "tests.catapult.mongo.plugins.transfer" in directory /Users/sergeyumarov/catapult-server-master/extensions/mongo/plugins/transfer/tests
    linked by target "catapult.mongo" in directory /Users/sergeyumarov/catapult-server-master/extensions/mongo/src
    linked by target "tests.catapult.mongo" in directory /Users/sergeyumarov/catapult-server-master/extensions/mongo/tests
    linked by target "tests.catapult.int.mongo" in directory /Users/sergeyumarov/catapult-server-master/extensions/mongo/tests/int
    linked by target "tests.catapult.test.mongo" in directory /Users/sergeyumarov/catapult-server-master/extensions/mongo/tests/test
MONGOCXX_LIB
    linked by target "extension.mongo" in directory /Users/sergeyumarov/catapult-server-master/extensions/mongo
    linked by target "catapult.mongo.plugins.aggregate" in directory /Users/sergeyumarov/catapult-server-master/extensions/mongo/plugins/aggregate/src
    linked by target "tests.catapult.mongo.plugins.aggregate" in directory /Users/sergeyumarov/catapult-server-master/extensions/mongo/plugins/aggregate/tests
    linked by target "catapult.mongo.plugins.lock.deps" in directory /Users/sergeyumarov/catapult-server-master/extensions/mongo/plugins/lock/src
    linked by target "tests.catapult.mongo.plugins.lock" in directory /Users/sergeyumarov/catapult-server-master/extensions/mongo/plugins/lock/tests
    linked by target "tests.catapult.int.mongo.plugins.lock" in directory /Users/sergeyumarov/catapult-server-master/extensions/mongo/plugins/lock/tests/int
    linked by target "tests.catapult.test.mongo.plugins.lock" in directory /Users/sergeyumarov/catapult-server-master/extensions/mongo/plugins/lock/tests/test
    linked by target "catapult.mongo.plugins.multisig.deps" in directory /Users/sergeyumarov/catapult-server-master/extensions/mongo/plugins/multisig/src
    linked by target "tests.catapult.mongo.plugins.multisig" in directory /Users/sergeyumarov/catapult-server-master/extensions/mongo/plugins/multisig/tests
    linked by target "tests.catapult.int.mongo.plugins.multisig" in directory /Users/sergeyumarov/catapult-server-master/extensions/mongo/plugins/multisig/tests/int
    linked by target "tests.catapult.test.mongo.plugins.multisig" in directory /Users/sergeyumarov/catapult-server-master/extensions/mongo/plugins/multisig/tests/test
    linked by target "catapult.mongo.plugins.namespace.deps" in directory /Users/sergeyumarov/catapult-server-master/extensions/mongo/plugins/namespace/src
    linked by target "tests.catapult.mongo.plugins.namespace" in directory /Users/sergeyumarov/catapult-server-master/extensions/mongo/plugins/namespace/tests
    linked by target "tests.catapult.int.mongo.plugins.namespace" in directory /Users/sergeyumarov/catapult-server-master/extensions/mongo/plugins/namespace/tests/int
    linked by target "tests.catapult.test.mongo.plugins.namespace" in directory /Users/sergeyumarov/catapult-server-master/extensions/mongo/plugins/namespace/tests/test
    linked by target "catapult.mongo.plugins.transfer" in directory /Users/sergeyumarov/catapult-server-master/extensions/mongo/plugins/transfer/src
    linked by target "tests.catapult.mongo.plugins.transfer" in directory /Users/sergeyumarov/catapult-server-master/extensions/mongo/plugins/transfer/tests
    linked by target "catapult.mongo" in directory /Users/sergeyumarov/catapult-server-master/extensions/mongo/src
    linked by target "tests.catapult.mongo" in directory /Users/sergeyumarov/catapult-server-master/extensions/mongo/tests
    linked by target "tests.catapult.int.mongo" in directory /Users/sergeyumarov/catapult-server-master/extensions/mongo/tests/int
    linked by target "tests.catapult.test.mongo" in directory /Users/sergeyumarov/catapult-server-master/extensions/mongo/tests/test

-- Configuring incomplete, errors occurred!

**Comment by jhkrischel** [comment]
This should work on a local ubuntu 18 vagrant box:

https://gitlab.com/he3labs-public/catapult-server-vagrant
