### ISSUE TITLE
NamespaceLifetime.GracePeriodEnd can overflow

### ISSUE THREAD

**Issue by proximax-core-dev** [nemtech/catapult-server#31]
/// Creates a lifetime with \a start height, \a end height and a grace period (\a gracePeriodDuration).
	NamespaceLifetime(Height start, Height end, BlockDuration gracePeriodDuration)
			: Start(start)
			, End(end)
			, GracePeriodEnd(end.unwrap() + gracePeriodDuration.unwrap()) {
		if (start >= end)
			CATAPULT_THROW_INVALID_ARGUMENT("namespace lifetime must be positive");
	}

The GracePeriodEnd can easy overflow if the End is Eternal and gracePeriodDuration > 0.
It can be easy fixed by:

	GracePeriodEnd(std::max(end.unwrap() + gracePeriodDuration.unwrap(), end.unwrap()))

**Comment by gimer** [comment]
In catapult eternal namespaces are not allowed after nemesis block (see RootNamespaceAvailabilityValidator) and afaik there are no plans to change this.
So in reality that overflow will happen only if end data is actually **invalid**. The check is there **deliberately**.

**Comment by proximax-core-dev** [comment]
We added ability to create eternal namespaces so we got this bug. 
The check is not perfect, because it doesn't catch case when End > start, but GracePeriodEnd <= start.

The fix is minor and can resolve bugs in future.

**Comment by gimer** [comment]
(reopened, cause we probably will reconsider this)

**Comment by Jaguar0625** [comment]
Fixed in dragon (95e0c6a).
