### ISSUE TITLE
Build error catapult dragon

### ISSUE THREAD

**Issue by slackale** [nemtech/catapult-server#38]
Greetings.
Got this error when trying to build dragon:

``[1/539] Linking CXX executable bin/tests.catapult.plugins.multisig
FAILED: bin/tests.catapult.plugins.multisig 
: && /usr/bin/c++  -Wall -Wextra -Werror -Wstrict-aliasing=1 -fvisibility=hidden                        -Wno-dangling-else -O3 -DNDEBUG -Wno-maybe-uninitialized  -Wl,--disable-new-dtags   -rdynamic src/catapult/version/nix/CMakeFiles/catapult.version.nix.dir/what_version.cpp.o plugins/txes/multisig/tests/CMakeFiles/tests.catapult.plugins.multisig.dir/cache/MultisigCacheStorageTests.cpp.o plugins/txes/multisig/tests/CMakeFiles/tests.catapult.plugins.multisig.dir/cache/MultisigCacheTests.cpp.o plugins/txes/multisig/tests/CMakeFiles/tests.catapult.plugins.multisig.dir/cache/MultisigCacheUtilsTests.cpp.o plugins/txes/multisig/tests/CMakeFiles/tests.catapult.plugins.multisig.dir/config/MultisigConfigurationTests.cpp.o plugins/txes/multisig/tests/CMakeFiles/tests.catapult.plugins.multisig.dir/model/ModifyMultisigAccountTransactionTests.cpp.o plugins/txes/multisig/tests/CMakeFiles/tests.catapult.plugins.multisig.dir/observers/ModifyMultisigCosignersObserverTests.cpp.o plugins/txes/multisig/tests/CMakeFiles/tests.catapult.plugins.multisig.dir/observers/ModifyMultisigSettingsObserverTests.cpp.o plugins/txes/multisig/tests/CMakeFiles/tests.catapult.plugins.multisig.dir/state/MultisigEntrySerializerTests.cpp.o plugins/txes/multisig/tests/CMakeFiles/tests.catapult.plugins.multisig.dir/state/MultisigEntryTests.cpp.o plugins/txes/multisig/tests/CMakeFiles/tests.catapult.plugins.multisig.dir/validators/ModifyMultisigCosignersValidatorTests.cpp.o plugins/txes/multisig/tests/CMakeFiles/tests.catapult.plugins.multisig.dir/validators/ModifyMultisigInvalidCosignersValidatorTests.cpp.o plugins/txes/multisig/tests/CMakeFiles/tests.catapult.plugins.multisig.dir/validators/ModifyMultisigInvalidSettingsValidatorTests.cpp.o plugins/txes/multisig/tests/CMakeFiles/tests.catapult.plugins.multisig.dir/validators/ModifyMultisigLoopAndLevelValidatorTests.cpp.o plugins/txes/multisig/tests/CMakeFiles/tests.catapult.plugins.multisig.dir/validators/ModifyMultisigMaxCosignedAccountsValidatorTests.cpp.o plugins/txes/multisig/tests/CMakeFiles/tests.catapult.plugins.multisig.dir/validators/ModifyMultisigMaxCosignersValidatorTests.cpp.o plugins/txes/multisig/tests/CMakeFiles/tests.catapult.plugins.multisig.dir/validators/MultisigAggregateEligibleCosignersValidatorTests.cpp.o plugins/txes/multisig/tests/CMakeFiles/tests.catapult.plugins.multisig.dir/validators/MultisigAggregateSufficientCosignersValidatorTests.cpp.o plugins/txes/multisig/tests/CMakeFiles/tests.catapult.plugins.multisig.dir/validators/MultisigPermittedOperationValidatorTests.cpp.o plugins/txes/multisig/tests/CMakeFiles/tests.catapult.plugins.multisig.dir/test/MultisigTestUtils.cpp.o plugins/txes/multisig/tests/CMakeFiles/tests.catapult.plugins.multisig.dir/plugins/ModifyMultisigAccountTransactionPluginTests.cpp.o plugins/txes/multisig/tests/CMakeFiles/tests.catapult.plugins.multisig.dir/plugins/MultisigPluginTests.cpp.o  -o bin/tests.catapult.plugins.multisig  -Wl,-rpath,"\$ORIGIN:\$ORIGIN/deps:/root/boost-build-1.69.0/lib:/usr/local/lib" /usr/local/lib/libgtest.a lib/libtests.catapult.test.cache.a bin/libcatapult.plugins.multisig.so /root/boost-build-1.69.0/lib/libboost_atomic.so /root/boost-build-1.69.0/lib/libboost_system.so /root/boost-build-1.69.0/lib/libboost_date_time.so /root/boost-build-1.69.0/lib/libboost_regex.so /root/boost-build-1.69.0/lib/libboost_timer.so /root/boost-build-1.69.0/lib/libboost_chrono.so /root/boost-build-1.69.0/lib/libboost_log.so /root/boost-build-1.69.0/lib/libboost_thread.so /root/boost-build-1.69.0/lib/libboost_filesystem.so /root/boost-build-1.69.0/lib/libboost_program_options.so /root/boost-build-1.69.0/lib/libboost_log_setup.so -lpthread lib/libtests.catapult.test.core.a lib/libtests.catapult.test.nodeps.a lib/libcatapult.version.a lib/libcatapult.sdk.a bin/libcatapult.plugins.aggregate.so lib/libcatapult.plugins.aggregate.deps.a lib/libcatapult.plugins.aggregate.sdk.a lib/libcatapult.plugins.mosaic.sdk.a lib/libcatapult.plugins.namespace.sdk.a lib/libcatapult.plugins.property.sdk.a lib/libcatapult.plugins.multisig.deps.a lib/libcatapult.plugins.a lib/libcatapult.coresystem.a lib/libcatapult.plugins.a lib/libcatapult.coresystem.a -ldl lib/libcatapult.cache_core.a lib/libcatapult.config.a lib/libcatapult.observers.a lib/libcatapult.state.a lib/libcatapult.validators.a lib/libcatapult.cache.a lib/libcatapult.io.a lib/libcatapult.cache_db.a /usr/local/lib/librocksdb.so lib/libcatapult.tree.a lib/libcatapult.ionet.a lib/libcatapult.thread.a lib/libcatapult.ionet.a lib/libcatapult.thread.a lib/libcatapult.model.a lib/libcatapult.crypto.a lib/libexternal.a lib/libcatapult.utils.a /root/boost-build-1.69.0/lib/libboost_atomic.so /root/boost-build-1.69.0/lib/libboost_system.so /root/boost-build-1.69.0/lib/libboost_date_time.so /root/boost-build-1.69.0/lib/libboost_regex.so /root/boost-build-1.69.0/lib/libboost_timer.so /root/boost-build-1.69.0/lib/libboost_chrono.so /root/boost-build-1.69.0/lib/libboost_log.so /root/boost-build-1.69.0/lib/libboost_thread.so /root/boost-build-1.69.0/lib/libboost_filesystem.so /root/boost-build-1.69.0/lib/libboost_program_options.so /root/boost-build-1.69.0/lib/libboost_log_setup.so -lpthread && cd /opt/catapult-server-0.4.0.1/_build/plugins/txes/multisig/tests && /usr/bin/cmake -E copy_if_different /root/boost-build-1.69.0/lib/libboost_atomic.so /opt/catapult-server-0.4.0.1/_build/bin/boost && cd /opt/catapult-server-0.4.0.1/_build/plugins/txes/multisig/tests && /usr/bin/cmake -E copy_if_different /root/boost-build-1.69.0/lib/libboost_system.so /opt/catapult-server-0.4.0.1/_build/bin/boost && cd /opt/catapult-server-0.4.0.1/_build/plugins/txes/multisig/tests && /usr/bin/cmake -E copy_if_different /root/boost-build-1.69.0/lib/libboost_date_time.so /opt/catapult-server-0.4.0.1/_build/bin/boost && cd /opt/catapult-server-0.4.0.1/_build/plugins/txes/multisig/tests && /usr/bin/cmake -E copy_if_different /root/boost-build-1.69.0/lib/libboost_regex.so /opt/catapult-server-0.4.0.1/_build/bin/boost && cd /opt/catapult-server-0.4.0.1/_build/plugins/txes/multisig/tests && /usr/bin/cmake -E copy_if_different /root/boost-build-1.69.0/lib/libboost_timer.so /opt/catapult-server-0.4.0.1/_build/bin/boost && cd /opt/catapult-server-0.4.0.1/_build/plugins/txes/multisig/tests && /usr/bin/cmake -E copy_if_different /root/boost-build-1.69.0/lib/libboost_chrono.so /opt/catapult-server-0.4.0.1/_build/bin/boost && cd /opt/catapult-server-0.4.0.1/_build/plugins/txes/multisig/tests && /usr/bin/cmake -E copy_if_different /root/boost-build-1.69.0/lib/libboost_log.so /opt/catapult-server-0.4.0.1/_build/bin/boost && cd /opt/catapult-server-0.4.0.1/_build/plugins/txes/multisig/tests && /usr/bin/cmake -E copy_if_different /root/boost-build-1.69.0/lib/libboost_thread.so /opt/catapult-server-0.4.0.1/_build/bin/boost && cd /opt/catapult-server-0.4.0.1/_build/plugins/txes/multisig/tests && /usr/bin/cmake -E copy_if_different /root/boost-build-1.69.0/lib/libboost_filesystem.so /opt/catapult-server-0.4.0.1/_build/bin/boost && cd /opt/catapult-server-0.4.0.1/_build/plugins/txes/multisig/tests && /usr/bin/cmake -E copy_if_different /root/boost-build-1.69.0/lib/libboost_program_options.so /opt/catapult-server-0.4.0.1/_build/bin/boost
lib/libtests.catapult.test.cache.a(UtTestUtils.cpp.o): In function `catapult::test::(anonymous namespace)::AssertContainsAll(catapult::cache::MemoryUtCacheView const&, std::vector<catapult::utils::ByteArray<32ul, catapult::Hash256_tag>, std::allocator<catapult::utils::ByteArray<32ul, catapult::Hash256_tag> > > const&, bool)':
UtTestUtils.cpp:(.text+0x391): undefined reference to `catapult::cache::MemoryUtCacheView::contains(catapult::utils::ByteArray<32ul, catapult::Hash256_tag> const&) const'
UtTestUtils.cpp:(.text+0x3c6): undefined reference to `catapult::cache::MemoryUtCacheView::contains(catapult::utils::ByteArray<32ul, catapult::Hash256_tag> const&) const'
lib/libtests.catapult.test.cache.a(UtTestUtils.cpp.o): In function `catapult::test::ExtractTransactionInfos(catapult::cache::MemoryUtCacheView const&, unsigned long)':
UtTestUtils.cpp:(.text+0xa66): undefined reference to `catapult::cache::MemoryUtCacheView::forEach(std::function<bool (catapult::model::TransactionInfo const&)> const&) const'
lib/libtests.catapult.test.cache.a(UtTestUtils.cpp.o): In function `catapult::test::CreateSeededMemoryUtCache(unsigned int)':
UtTestUtils.cpp:(.text+0xb29): undefined reference to `catapult::cache::MemoryUtCache::MemoryUtCache(catapult::cache::MemoryCacheOptions const&)'
lib/libtests.catapult.test.cache.a(UtTestUtils.cpp.o): In function `catapult::test::AssertContainsAll(catapult::cache::MemoryUtCache const&, std::vector<catapult::utils::ByteArray<32ul, catapult::Hash256_tag>, std::allocator<catapult::utils::ByteArray<32ul, catapult::Hash256_tag> > > const&)':
UtTestUtils.cpp:(.text+0xdf3): undefined reference to `catapult::cache::MemoryUtCache::view() const'
lib/libtests.catapult.test.cache.a(UtTestUtils.cpp.o): In function `catapult::test::AssertContainsNone(catapult::cache::MemoryUtCache const&, std::vector<catapult::utils::ByteArray<32ul, catapult::Hash256_tag>, std::allocator<catapult::utils::ByteArray<32ul, catapult::Hash256_tag> > > const&)':
UtTestUtils.cpp:(.text+0xe63): undefined reference to `catapult::cache::MemoryUtCache::view() const'
lib/libtests.catapult.test.cache.a(UtTestUtils.cpp.o): In function `catapult::test::(anonymous namespace)::AssertContainsAll(catapult::cache::MemoryUtCache const&, std::vector<catapult::model::TransactionInfo, std::allocator<catapult::model::TransactionInfo> > const&, bool)':
UtTestUtils.cpp:(.text+0xee6): undefined reference to `catapult::cache::MemoryUtCache::view() const'
UtTestUtils.cpp:(.text+0xf31): undefined reference to `catapult::cache::MemoryUtCacheView::contains(catapult::utils::ByteArray<32ul, catapult::Hash256_tag> const&) const'
UtTestUtils.cpp:(.text+0xf67): undefined reference to `catapult::cache::MemoryUtCacheView::contains(catapult::utils::ByteArray<32ul, catapult::Hash256_tag> const&) const'
lib/libtests.catapult.test.cache.a(UtTestUtils.cpp.o): In function `catapult::test::ExtractRawDeadlines(catapult::cache::MemoryUtCache const&)':
UtTestUtils.cpp:(.text+0x1323): undefined reference to `catapult::cache::MemoryUtCache::view() const'
UtTestUtils.cpp:(.text+0x1360): undefined reference to `catapult::cache::MemoryUtCacheView::forEach(std::function<bool (catapult::model::TransactionInfo const&)> const&) const'
lib/libtests.catapult.test.cache.a(UtTestUtils.cpp.o): In function `catapult::test::ExtractTransactions(catapult::cache::MemoryUtCache const&, unsigned long)':
UtTestUtils.cpp:(.text+0x1436): undefined reference to `catapult::cache::MemoryUtCache::view() const'
UtTestUtils.cpp:(.text+0x147d): undefined reference to `catapult::cache::MemoryUtCacheView::forEach(std::function<bool (catapult::model::TransactionInfo const&)> const&) const'
lib/libtests.catapult.test.cache.a(UtTestUtils.cpp.o): In function `catapult::test::AssertDeadlines(catapult::cache::MemoryUtCache const&, std::vector<unsigned long, std::allocator<unsigned long> > const&)':
UtTestUtils.cpp:(.text+0x1571): undefined reference to `catapult::cache::MemoryUtCache::view() const'
UtTestUtils.cpp:(.text+0x15b3): undefined reference to `catapult::cache::MemoryUtCacheView::forEach(std::function<bool (catapult::model::TransactionInfo const&)> const&) const'
collect2: error: ld returned 1 exit status
[4/539] Building CXX object plugins/txes/namespace/src/CMakeFiles/catapult.plugins.namespace.deps.dir/validators/AliasAvailabilityValidator.cpp.o
ninja: build stopped: subcommand failed.``

DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=18.04
DISTRIB_CODENAME=bionic
DISTRIB_DESCRIPTION="Ubuntu 18.04.2 LTS"

Thank you.

**Comment by gimer** [comment]
a) you *should* be able to attach files to issues (i.e. with .txt extension) - would make it much more readable...
b) there is something missing in the log
c) what is the compiler that you're using

**Comment by slackale** [comment]
I just followed building guide in the readme.md here, exactly what it says:
"cmake -DBOOST_ROOT=~/boost-build-1.69.0 -DCMAKE_BUILD_TYPE=Release -G Ninja ..
ninja publish
ninja -j4"
[CMakeError.log](https://github.com/nemtech/catapult-server/files/3262486/CMakeError.log)
[CMakeOutput.log](https://github.com/nemtech/catapult-server/files/3262487/CMakeOutput.log)

**Comment by gimer** [comment]
ok, compiler looks fine.
When running cmake - **did it report an error** (asking cause you have attached `CMakeError.log`)
If it did, how were you able to run `ninja` (or whatever build tool you're using) afterwards?

**Comment by slackale** [comment]
Hmm no errors but a lot of warnings like this one:

``CMake Warning at /usr/share/cmake-3.10/Modules/FindBoost.cmake:801 (message):
  New Boost version may have incorrect or missing dependencies and imported
  targets
Call Stack (most recent call first):
  /usr/share/cmake-3.10/Modules/FindBoost.cmake:907 (_Boost_COMPONENT_DEPENDENCIES)
  /usr/share/cmake-3.10/Modules/FindBoost.cmake:1558 (_Boost_MISSING_DEPENDENCIES)
  CMakeLists.txt:17 (find_package)``

**Comment by gimer** [comment]
this one is due to old cmake (1), but should be safe to ignore

(1) - we'll update instruction to suggest to install build or install cmake from binaries, cause 3.10 present in ubuntu is an ancient one

**Comment by CrackTheCode016** [comment]
Reporting similar errors on Debian Stretch with `cmake-3.7.2` after Catapult tries to find dependencies.   I receive the following errors regarding boost despite pointing it to the correct dir for `BOOST_ROOT`: 

```
**<- i.e, I get a bunch of these... ->**

CMake Warning at /usr/share/cmake-3.7/Modules/FindBoost.cmake:761 (message):
  Imported targets not available for Boost version 106900
Call Stack (most recent call first):
  /usr/share/cmake-3.7/Modules/FindBoost.cmake:865 (_Boost_COMPONENT_DEPENDENCIES)
  /usr/share/cmake-3.7/Modules/FindBoost.cmake:1470 (_Boost_MISSING_DEPENDENCIES)
  CMakeLists.txt:17 (find_package)
```


```
**<- Then at the end of find_package() for boost, this happens even tho we are correctly referencing the dir and the static libs exist: ->**

CMake Error at /usr/share/cmake-3.7/Modules/FindBoost.cmake:1831 (message):
  Unable to find the requested Boost libraries.

  Boost version: 1.69.0

  Boost include path: /home/pi/boost-build-1.69.0/include

  Could not find the following Boost libraries:

          boost_regex
          boost_timer
          boost_log
          boost_filesystem
          boost_program_options
```

**Comment by gimer** [comment]
@CrackTheCode016 that seems to be unrelated to problem he is experiencing. Cmake 3.7 at this point is ANCIENT, update to something newer, don't use cmake provided in distribution packages.

**Comment by gimer** [comment]
@slackale are there any errors reported by cmake?
where did you got CMakeError.log from?
do you have *clean* build directory?

**Comment by mijinc0** [comment]
Greetings.

I probably received the same error as @slackale (but I used make)

It seemed like a link error. So I added `catapult.cache_tx` to` tests.catapult.test.cache` targt, and then the build reached 100%.  

```
# catapult-server/tests/test/cache/CMakeLists.txt
 
cmake_minimum_required(VERSION 3.2)

catapult_library_target(tests.catapult.test.cache)

# add "catapult.cache_tx"
target_link_libraries(tests.catapult.test.cache tests.catapult.test.core catapult.cache catapult.cache_core catapult.cache_tx)
```

I do not know if this is the right way, but I will be happy if this information is useful to you :)

### env

```
Ubuntu 18.04.2 LTS
cmake version 3.10.2
GNU Make 4.1
```

### error

```
$ cmake -DBOOST_ROOT=/tmp/boost-build-1.69.0 -DCMAKE_BUILD_TYPE=Release ..
$ make publish
$ make tests.catapult.plugins.multisig -j3
Scanning dependencies of target external
Scanning dependencies of target catapult.state
Scanning dependencies of target catapult.utils
[  5%] Building C object external/CMakeFiles/external.dir/ref10/crypto_verify_32.c.o
[  5%] Building C object external/CMakeFiles/external.dir/ref10/fe_0.c.o
[  5%] Building C object external/CMakeFiles/external.dir/ref10/fe_1.c.o
[  5%] Building C object external/CMakeFiles/external.dir/ref10/fe_add.c.o

...

[100%] Building CXX object plugins/txes/multisig/tests/CMakeFiles/tests.catapult.plugins.multisig.dir/plugins/ModifyMultisigAccountTransactionPluginTests.cpp.o
[100%] Building CXX object plugins/txes/multisig/tests/CMakeFiles/tests.catapult.plugins.multisig.dir/plugins/MultisigPluginTests.cpp.o
[100%] Linking CXX executable ../../../../bin/tests.catapult.plugins.multisig
../../../../lib/libtests.catapult.test.cache.a(UtTestUtils.cpp.o): In function `catapult::test::(anonymous namespace)::AssertContainsAll(catapult::cache::MemoryUtCacheView const&, std::vector<catapult::utils::ByteArray<32ul, catapult::Hash256_tag>, std::allocator<catapult::utils::ByteArray<32ul, catapult::Hash256_tag> > > const&, bool)':
UtTestUtils.cpp:(.text+0x391): undefined reference to `catapult::cache::MemoryUtCacheView::contains(catapult::utils::ByteArray<32ul, catapult::Hash256_tag> const&) const'
UtTestUtils.cpp:(.text+0x3c6): undefined reference to `catapult::cache::MemoryUtCacheView::contains(catapult::utils::ByteArray<32ul, catapult::Hash256_tag> const&) const'
../../../../lib/libtests.catapult.test.cache.a(UtTestUtils.cpp.o): In function `catapult::test::ExtractTransactionInfos(catapult::cache::MemoryUtCacheView const&, unsigned long)':
UtTestUtils.cpp:(.text+0xa66): undefined reference to `catapult::cache::MemoryUtCacheView::forEach(std::function<bool (catapult::model::TransactionInfo const&)> const&) const'
../../../../lib/libtests.catapult.test.cache.a(UtTestUtils.cpp.o): In function `catapult::test::CreateSeededMemoryUtCache(unsigned int)':
UtTestUtils.cpp:(.text+0xb29): undefined reference to `catapult::cache::MemoryUtCache::MemoryUtCache(catapult::cache::MemoryCacheOptions const&)'
../../../../lib/libtests.catapult.test.cache.a(UtTestUtils.cpp.o): In function `catapult::test::AssertContainsAll(catapult::cache::MemoryUtCache const&, std::vector<catapult::utils::ByteArray<32ul, catapult::Hash256_tag>, std::allocator<catapult::utils::ByteArray<32ul, catapult::Hash256_tag> > > const&)':
UtTestUtils.cpp:(.text+0xdf3): undefined reference to `catapult::cache::MemoryUtCache::view() const'
../../../../lib/libtests.catapult.test.cache.a(UtTestUtils.cpp.o): In function `catapult::test::AssertContainsNone(catapult::cache::MemoryUtCache const&, std::vector<catapult::utils::ByteArray<32ul, catapult::Hash256_tag>, std::allocator<catapult::utils::ByteArray<32ul, catapult::Hash256_tag> > > const&)':
UtTestUtils.cpp:(.text+0xe63): undefined reference to `catapult::cache::MemoryUtCache::view() const'
../../../../lib/libtests.catapult.test.cache.a(UtTestUtils.cpp.o): In function `catapult::test::(anonymous namespace)::AssertContainsAll(catapult::cache::MemoryUtCache const&, std::vector<catapult::model::TransactionInfo, std::allocator<catapult::model::TransactionInfo> > const&, bool)':
UtTestUtils.cpp:(.text+0xee6): undefined reference to `catapult::cache::MemoryUtCache::view() const'
UtTestUtils.cpp:(.text+0xf31): undefined reference to `catapult::cache::MemoryUtCacheView::contains(catapult::utils::ByteArray<32ul, catapult::Hash256_tag> const&) const'
UtTestUtils.cpp:(.text+0xf67): undefined reference to `catapult::cache::MemoryUtCacheView::contains(catapult::utils::ByteArray<32ul, catapult::Hash256_tag> const&) const'
../../../../lib/libtests.catapult.test.cache.a(UtTestUtils.cpp.o): In function `catapult::test::ExtractRawDeadlines(catapult::cache::MemoryUtCache const&)':
UtTestUtils.cpp:(.text+0x1323): undefined reference to `catapult::cache::MemoryUtCache::view() const'
UtTestUtils.cpp:(.text+0x1360): undefined reference to `catapult::cache::MemoryUtCacheView::forEach(std::function<bool (catapult::model::TransactionInfo const&)> const&) const'
../../../../lib/libtests.catapult.test.cache.a(UtTestUtils.cpp.o): In function `catapult::test::ExtractTransactions(catapult::cache::MemoryUtCache const&, unsigned long)':
UtTestUtils.cpp:(.text+0x1436): undefined reference to `catapult::cache::MemoryUtCache::view() const'
UtTestUtils.cpp:(.text+0x147d): undefined reference to `catapult::cache::MemoryUtCacheView::forEach(std::function<bool (catapult::model::TransactionInfo const&)> const&) const'
../../../../lib/libtests.catapult.test.cache.a(UtTestUtils.cpp.o): In function `catapult::test::AssertDeadlines(catapult::cache::MemoryUtCache const&, std::vector<unsigned long, std::allocator<unsigned long> > const&)':
UtTestUtils.cpp:(.text+0x1571): undefined reference to `catapult::cache::MemoryUtCache::view() const'
UtTestUtils.cpp:(.text+0x15b3): undefined reference to `catapult::cache::MemoryUtCacheView::forEach(std::function<bool (catapult::model::TransactionInfo const&)> const&) const'
collect2: error: ld returned 1 exit status
plugins/txes/multisig/tests/CMakeFiles/tests.catapult.plugins.multisig.dir/build.make:676: recipe for target 'bin/tests.catapult.plugins.multisig' failed
make[3]: *** [bin/tests.catapult.plugins.multisig] Error 1
CMakeFiles/Makefile2:8684: recipe for target 'plugins/txes/multisig/tests/CMakeFiles/tests.catapult.plugins.multisig.dir/all' failed
make[2]: *** [plugins/txes/multisig/tests/CMakeFiles/tests.catapult.plugins.multisig.dir/all] Error 2
CMakeFiles/Makefile2:8696: recipe for target 'plugins/txes/multisig/tests/CMakeFiles/tests.catapult.plugins.multisig.dir/rule' failed
make[1]: *** [plugins/txes/multisig/tests/CMakeFiles/tests.catapult.plugins.multisig.dir/rule] Error 2
Makefile:1559: recipe for target 'tests.catapult.plugins.multisig' failed
make: *** [tests.catapult.plugins.multisig] Error 2
```

**Comment by gimer** [comment]
@mijinc0 hi and thanks for your input 🖖. 

Your fix seems correct 👍, now we're trying to find out, why it's actually compiling in our environment ^^.

**Comment by slackale** [comment]
> catapult.cache_tx

Tried this and it worked, Thank you very much.

**Comment by gimer** [comment]
hey, please don't close, we still need to address this ;-)

**Comment by gimer** [comment]
fixed along with other cmake fixes, will be present in next build

**Comment by gimer** [comment]
fixed in elephant.1
