### ISSUE TITLE
Chain height not increasing catapult 0.4

### ISSUE THREAD

**Issue by Eliptica** [nemtech/catapult-server#41]
Greetings.
I hope you can help me with this issue not sure if this is the right forum.
I was able to build and run Catapult Server 0.4 Dragon but chain height is not increasing as it always stays at Height 1 - Score 1
Configuration is same as 0.3 where it worked fine.

ISSUE: Chain height not increasing
CONFIGURATION: Same as 0.3.0.2

FILES MODIFIED: 
    • config-extensions-server.properties: To enable “extension.harvesting” in peernode01 and api extensions in apinode01
    • config-harvesting.properties: set private key in “harvestKey” and public key in “beneficiary”
config-network.properties: modified “totalChainImportance” from 15’000’000 to 17’000’000 (Server does not start if left original value)
    • config-node.properties: set “friendlyName”
    • config-user.properties: set private key in “bootKey”
    • peers-p2p.json: set “publicKey” and “host” for both peernodes
    • peers-p2p.json: set “publicKey” and “host” for apinode

NOTE: There’s a new parameter “beneficiary” in config-harvesting.properties. We tried setting a public key from one of the genesis accounts and also another account not from genesis.

Servers start without errors but chain height is not increasing as it always stay at height 1 – Score 1

[catapult_server0019.log](https://github.com/nemtech/catapult-server/files/3297727/catapult_server0019.log)

Alejandro Gomez
Eliptica S.A.

**Comment by gimer** [comment]
Can you attach log with level set to Debug?

**Comment by BloodyRookie** [comment]
`config-harvesting.properties: set private key in “harvestKey” and public key in “beneficiary”`
how about `isAutoHarvestingEnabled`, did you set it to true?

**Comment by Eliptica** [comment]
> `config-harvesting.properties: set private key in “harvestKey” and public key in “beneficiary”`
> how about `isAutoHarvestingEnabled`, did you set it to true?

Yeah, you can also see in the log that it actually says "Unlocked harvesting account 9BD9F229101A745B122122D0B75B2FF5E24A61C68F68D97642A03D93D1E257FC for harvesting with result Success"

**Comment by BloodyRookie** [comment]
if you are running a 2 core server then the broker will hang after a while and thus there are no new blocks stored in the mongodb. We will fix that #soon

**Comment by Eliptica** [comment]
> Can you attach log with level set to Debug?

Sure
Log level = Debug and net = Debug
peernode01 - peernode02 - apinode01

[catapult_server0014.log](https://github.com/nemtech/catapult-server/files/3301829/catapult_server0014.log)
[catapult_server0017.log](https://github.com/nemtech/catapult-server/files/3301830/catapult_server0017.log)
[catapult_server0028.log](https://github.com/nemtech/catapult-server/files/3301831/catapult_server0028.log)

**Comment by BloodyRookie** [comment]
`pruned 1 unlocked accounts`

looks like the accounts used for harvesting don't have enough currency

**Comment by Eliptica** [comment]
> `pruned 1 unlocked accounts`
> 
> looks like the accounts used for harvesting don't have enough currency

Thank you.

Ok, I just set one of the genesis accounts private key and it now harvest block 2 but it throws an error:
"<error> (io::FileBlockStorage.cpp@221) Throwing exception: cannot save block with height 2 when storage height is 0"

[catapult_server0029.log](https://github.com/nemtech/catapult-server/files/3301933/catapult_server0029.log)

**Comment by BloodyRookie** [comment]
check that you have the correct index.dat and in folder 00000 the files 00001.dat and hashes.dat

**Comment by Eliptica** [comment]
> check that you have the correct index.dat and in folder 00000 the files 00001.dat and hashes.dat

Ok it is working now, thank you very much !

**Comment by jontey** [comment]
For inconsistent state hash, I would usually check if the `config-network.properties` file is the same on both peers

**Comment by Eliptica** [comment]
> For inconsistent state hash, I would usually check if the `config-network.properties` file is the same on both peers

You're right ! I had a different value on "harvestBeneficiaryPercentage" Thank you very much !
