### ISSUE TITLE
Enhance build documentation

### ISSUE THREAD

**Issue by kaiyzen** [nemtech/catapult-server#46]
Its come up a few times past couple months and recently in conversations with community folks that more build related material for server might be warranted.  Currently we have these resources:

Build Instructions:

https://github.com/nemtech/catapult-server/blob/master/BUILDING.md

Building Image:

https://github.com/nemtech/docker-base-images

It would be good for those interested to post questions and issues so we can prioritize any out of date or missing details.

Also, if any community members have their own build experiences and any related content around it please share with the community and we can add to the docs or appropriate locations

**Comment by fullcircle23** [comment]
This was my experience building Catapult on MacOS about 8 months ago: https://github.com/fullcircle23/catapult-server-macos
I haven't tested it on the latest release but I believe others have.

**Comment by dl-nice** [comment]
I tried it on Macos and it was possible to build it successfully.https://github.com/nemtech/catapult-server/blob/master/BUILDING.md

**Comment by Jaguar0625** [comment]
Fixed in 621ccbd [v0.9.0.1].
