### ISSUE TITLE
Failure_Transfer_Out_Of_Order_Mosaics banning all of the node's clients

### ISSUE THREAD

**Issue by decentraliser** [nemtech/catapult-server#47]
-IP1 announces a transfer with desktop wallet, account A1, to node A, succeeds

-IP2 announces a transfer with desktop wallet, account A2, to node A, with 2 mosaics, the network currency being in the second position of the mosaics array.

-A throws `Failure_Transfer_Out_Of_Order_Mosaics`

-IP1 and IP2 can not announce transactions anymore, but they can GET data from the rest and WebSockets are still up

**Comment by Jaguar0625** [comment]
as temporary mitigation, can turn off node banning by changing config-node:banning:defaultBanDuration to 0

**Comment by Jaguar0625** [comment]
Fixed in 621ccbd [v0.9.0.1].
