### ISSUE TITLE
Unable to unbind aliases from expired mosaics

### ISSUE THREAD

**Issue by decentraliser** [nemtech/catapult-server#48]
Issue: can not unbind an alias from an expired mosaic

The mosaic `0550A29A06E0A16E` is aliased with `disposable.coin`
http://api-01.mt.ap-northeast-1.nemtech.network:3000/mosaic/names

The mosaic expired at block 46,989
http://api-01.mt.ap-northeast-1.nemtech.network:3000/mosaic

I think that an alias staying on an expired mosaic might make sense. However, I expect to be able to unbind it.
But when I announce the MosaicAliasTransaction, in a way that works for non-expired mosaics, the error "failure_mosaic_expired" is thrown

![image](https://user-images.githubusercontent.com/36499647/67136600-074ddd80-f25b-11e9-98fc-9c547f759e96.png)

**Comment by Jaguar0625** [comment]
Fixed in 621ccbd [v0.9.0.1].
