### ISSUE TITLE
AccountRestrictionMosaic transaction can (incorrectly) be created with zero modifications

### ISSUE THREAD

**Issue by ravitej-aluru** [nemtech/catapult-server#49]
Description: When a user creates a transaction to add AccountRestrictionMosaic, the user is not alerted even if there are no modifications in the submitted transaction

Steps:
  Scenario: An account blocks receiving transactions containing a specific asset
  Given Alex has the following assets registered and active:
      | ticket              |
      | voucher          |    
  When Bobby blocks receiving transactions containing no assets
  Then Bobby should receive the error "Failure_RestrictionAccount_Invalid_Modification" (or something similar along these lines)

Actual Outcome: The transaction goes through without any errors and the accountRestriction collection in the database contains zero elements for the modifications node.
**The user will be under the impression that a restriction has been added to the account when in fact it is not. From usability perspective, I think it is important to let the user know by way of an error message or at least a warning that the restriction will actually not result in any restriction.**

Please see the conversation in Slack using the link below for more [details.](https://nem2.slack.com/archives/CF1KY4EJJ/p1571841371000700)

**Comment by Jaguar0625** [comment]
Fixed in 621ccbd [v0.9.0.1].
