### ISSUE TITLE
Proposed Change: Address Tool Unknown Network

### ISSUE THREAD

**Issue by spentak** [nemtech/catapult-server#5]
The Address tool is very cool, but I would consider it broken.

To use the address tool you might do this:

```bash
/catapult/bin/catapult.tools.address --generate=20 -n my-new-network > /addresses/addresses.txt
```

This would throw an error though, because the source code only allows pre-defined networks:

`public (default), public-test, mijin, mijin-test`

So the utility of the tool is broken in my opinion.

Can I propose removing hard-coded `NetworkIdentifier` and instead read it from a file:

```c
const std::array<std::pair<const char*, NetworkIdentifier>, 4> String_To_Network_Identifier_Pairs{{
			{ "mijin", NetworkIdentifier::Blockstart },
			{ "mijin-test", NetworkIdentifier::Blockstart_Test },
			{ "public", NetworkIdentifier::Public },
			{ "public-test", NetworkIdentifier::Public_Test }
		}};
```

and if not that at least removing the code that throws an error so the tool can be used to generate addresses with any networkId:

```c
if (!model::TryParseValue(m_networkName, networkId))
					CATAPULT_THROW_INVALID_ARGUMENT_1("unknown network", m_networkName);
```

If you think this is a good change, I would like to code it and submit a PR. What do you think?

**Comment by gimer** [comment]
possible, but right now server in many places relies on using one of 4 predefined networks, so not sure how it will help you
