### ISSUE TITLE
Change maxCosignedAccountsPerAccount from uint8 to uint32

### ISSUE THREAD

**Issue by PaulRieger** [nemtech/catapult-server#51]
The current limit is too low for custodian use cases that involve HSMs for key storage/signing.

If it is undesirable to change the type for the master branch then maybe it could be introduced as a build flag?

**Comment by gimer** [comment]
It is **strongly** suggested not to use single account that is cosignatory of multiple accounts.
Even if you use HSM, it should easily handle multiple keys, and if not you could easily derive 'sub' keys using PBKDF2 or [Balloon hashing](https://en.wikipedia.org/wiki/Balloon_hashing)

Official implementation will *not* have those changed into `uint8`s.

> as a build flag?

that is possible, but it should be noted, that high values  are  NOT without performance penalty.

**Comment by PaulRieger** [comment]
Derivation won't always be possible since it would need to happen on the HSM if key exposure in runtime is to be avoided. 

Storing multiple keys on the HSM is possible but there's 1) always a limit and 2) procedures and policies that can make it impracticable to store thousands of keys.

An optional build flag seems to provide a good tradeoff between flexibility for use cases and providing a safe and performant default.

**Comment by Jaguar0625** [comment]
this is changed in https://github.com/nemtech/catapult-server/commit/0c757e6e25bde166b4d5f4396c01dba87f880880
