### ISSUE TITLE
Empty restrictions added to accountRestrictions collection

### ISSUE THREAD

**Issue by ravitej-aluru** [nemtech/catapult-server#53]
Description: When I create an AccountRestrictionMosaic, other restrictions are added to the database.

Steps:
Please note that user Bobby and mosaics ticket and voucher are freshly created on the network. So, there are no associated previous transactions for either the user or the mosaics.
1. Run the steps to create an AccountRestrictionMosaic as below:
Given Bobby blocks receiving transactions containing the following assets:
      | ticket  |
      | voucher |

2. Observe the accountRestrictions collection in catapult db 
**Actual Result:** Notice that 32769, 49153 and 49156 are created with empty values arrays.
**Expected Result:** Only restriction with non-empty values should make it to the database. And when restrictions are deleted, they should be removed from the database rather than leaving empty arrays around which can cause potential confusion.
> db.accountRestrictions.find().pretty()
{
	"_id" : ObjectId("5dd45def41178a3382363817"),
	"accountRestrictions" : {
		"address" : BinData(0,"kO2x2pFvJ/h3l+bi7MzPkkBGVOTDt8R2Cw=="),
		"restrictions" : [
			{
				"restrictionFlags" : 32769,
				"values" : [ ]
			},
			{
				"restrictionFlags" : 32770,
				"values" : [
					BinData(0,"EGRNOAXR1GM="),
					BinData(0,"nDRCA8rkYm4=")
				]
			},
			{
				"restrictionFlags" : 49153,
				"values" : [ ]
			},
			{
				"restrictionFlags" : 49156,
				"values" : [ ]
			}
		]
	}
}

**Comment by BloodyRookie** [comment]
Will be fixed next release

**Comment by gimer** [comment]
released in v0.9.1.1
