### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by BIMTrazer** [nemtech/catapult-server#60]
Greetings.
We are having an error when building latest catapult (Fushicho) server.
Following build guide exactly as it says

[2/1851] Building CXX object src/catapult/crypto/CMakeFiles/catapult.crypto.dir/OpensslContexts.cpp.o
FAILED: src/catapult/crypto/CMakeFiles/catapult.crypto.dir/OpensslContexts.cpp.o 
/usr/bin/c++  -DBOOST_ALL_DYN_LINK -D_STDC_WANT_LIB_EXT1_=1 -D__STDC_WANT_LIB_EXT1__=1 -I../ -I../src -I../src/catapult/crypto/../../../external -isystem /root/boost-build-1.71.0/include -Wall -Wextra -Werror -Wstrict-aliasing=1 -fvisibility=hidden -O3 -DNDEBUG -Wno-maybe-uninitialized -fPIC   -std=gnu++1z -MD -MT src/catapult/crypto/CMakeFiles/catapult.crypto.dir/OpensslContexts.cpp.o -MF src/catapult/crypto/CMakeFiles/catapult.crypto.dir/OpensslContexts.cpp.o.d -o src/catapult/crypto/CMakeFiles/catapult.crypto.dir/OpensslContexts.cpp.o -c ../src/catapult/crypto/OpensslContexts.cpp
../src/catapult/crypto/OpensslContexts.cpp:46:14: error: prototype for ‘EVP_MD_CTX* catapult::crypto::OpensslDigestContext::get()’ does not match any in class ‘catapult::crypto::OpensslDigestContext’
  EVP_MD_CTX* OpensslDigestContext::get() {
              ^~~~~~~~~~~~~~~~~~~~
In file included from ../src/catapult/crypto/OpensslContexts.cpp:21:0:
../src/catapult/crypto/OpensslContexts.h:51:18: error: candidate is: evp_md_ctx_st* catapult::crypto::OpensslDigestContext::get()
   evp_md_ctx_st* get();
                  ^~~
../src/catapult/crypto/OpensslContexts.cpp: In member function ‘void catapult::crypto::OpensslDigestContext::reset()’:
../src/catapult/crypto/OpensslContexts.cpp:51:3: error: ‘EVP_MD_CTX_reset’ was not declared in this scope
   EVP_MD_CTX_reset(get());
   ^~~~~~~~~~~~~~~~
../src/catapult/crypto/OpensslContexts.cpp:51:3: note: suggested alternative: ‘EVP_MD_CTX_create’
   EVP_MD_CTX_reset(get());
   ^~~~~~~~~~~~~~~~
   EVP_MD_CTX_create
../src/catapult/crypto/OpensslContexts.cpp: In member function ‘void catapult::crypto::OpensslCipherContext::reset()’:
../src/catapult/crypto/OpensslContexts.cpp:71:3: error: ‘EVP_CIPHER_CTX_reset’ was not declared in this scope
   EVP_CIPHER_CTX_reset(get());
   ^~~~~~~~~~~~~~~~~~~~
../src/catapult/crypto/OpensslContexts.cpp:71:3: note: suggested alternative: ‘EVP_CIPHER_CTX_free’
   EVP_CIPHER_CTX_reset(get());
   ^~~~~~~~~~~~~~~~~~~~
   EVP_CIPHER_CTX_free
[3/1851] Building CXX object src/catapult/crypto/CMakeFiles/catapult.crypto.dir/Hashes.cpp.o
FAILED: src/catapult/crypto/CMakeFiles/catapult.crypto.dir/Hashes.cpp.o 
/usr/bin/c++  -DBOOST_ALL_DYN_LINK -D_STDC_WANT_LIB_EXT1_=1 -D__STDC_WANT_LIB_EXT1__=1 -I../ -I../src -I../src/catapult/crypto/../../../external -isystem /root/boost-build-1.71.0/include -Wall -Wextra -Werror -Wstrict-aliasing=1 -fvisibility=hidden -O3 -DNDEBUG -Wno-maybe-uninitialized -fPIC   -std=gnu++1z -MD -MT src/catapult/crypto/CMakeFiles/catapult.crypto.dir/Hashes.cpp.o -MF src/catapult/crypto/CMakeFiles/catapult.crypto.dir/Hashes.cpp.o.d -o src/catapult/crypto/CMakeFiles/catapult.crypto.dir/Hashes.cpp.o -c ../src/catapult/crypto/Hashes.cpp
../src/catapult/crypto/Hashes.cpp: In function ‘void catapult::crypto::Sha3_256(const RawBuffer&, catapult::Hash256&)’:
../src/catapult/crypto/Hashes.cpp:81:20: error: ‘EVP_sha3_256’ was not declared in this scope
   HashSingleBuffer(EVP_sha3_256(), dataBuffer, hash);
                    ^~~~~~~~~~~~
../src/catapult/crypto/Hashes.cpp:81:20: note: suggested alternative: ‘EVP_sha256’
   HashSingleBuffer(EVP_sha3_256(), dataBuffer, hash);
                    ^~~~~~~~~~~~
                    EVP_sha256
../src/catapult/crypto/Hashes.cpp: In function ‘const EVP_MD* catapult::crypto::{anonymous}::GetMessageDigest(catapult::crypto::Sha3ModeTag, catapult::Hash256_tag)’:
../src/catapult/crypto/Hashes.cpp:99:11: error: ‘EVP_sha3_256’ was not declared in this scope
    return EVP_sha3_256();
           ^~~~~~~~~~~~
../src/catapult/crypto/Hashes.cpp:99:11: note: suggested alternative: ‘EVP_sha256’
    return EVP_sha3_256();
           ^~~~~~~~~~~~
           EVP_sha256
../src/catapult/crypto/Hashes.cpp: In function ‘const EVP_MD* catapult::crypto::{anonymous}::GetMessageDigest(catapult::crypto::Sha3ModeTag, catapult::GenerationHash_tag)’:
../src/catapult/crypto/Hashes.cpp:103:11: error: ‘EVP_sha3_256’ was not declared in this scope
    return EVP_sha3_256();
           ^~~~~~~~~~~~
../src/catapult/crypto/Hashes.cpp:103:11: note: suggested alternative: ‘EVP_sha256’
    return EVP_sha3_256();
           ^~~~~~~~~~~~
           EVP_sha256
In file included from ../src/catapult/crypto/Hashes.h:22:0,
                 from ../src/catapult/crypto/Hashes.cpp:21:
../src/catapult/crypto/OpensslContexts.h: In instantiation of ‘void catapult::crypto::OpensslDigestContext::dispatch(TFunc, TArgs&& ...) [with TFunc = int (*)(env_md_ctx_st*, const env_md_st*, engine_st*); TArgs = {const env_md_st*&, std::nullptr_t}]’:
../src/catapult/crypto/Hashes.cpp:48:20:   required from ‘void catapult::crypto::{anonymous}::HashSingleBuffer(const EVP_MD*, const RawBuffer&, THash&) [with THash = catapult::utils::ByteArray<catapult::Hash160_tag>; EVP_MD = env_md_st; catapult::utils::RawBuffer = catapult::utils::BasicRawBuffer<const unsigned char>]’
../src/catapult/crypto/Hashes.cpp:55:53:   required from here
../src/catapult/crypto/OpensslContexts.h:44:22: error: cannot convert ‘evp_md_ctx_st*’ to ‘env_md_ctx_st*’ in argument passing
    auto result = func(get(), std::forward<TArgs>(args)...);
                  ~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../src/catapult/crypto/OpensslContexts.h:25:8: note: class type ‘evp_md_ctx_st’ is incomplete
 struct evp_md_ctx_st;
        ^~~~~~~~~~~~~
../src/catapult/crypto/OpensslContexts.h: In instantiation of ‘void catapult::crypto::OpensslDigestContext::dispatch(TFunc, TArgs&& ...) [with TFunc = int (*)(env_md_ctx_st*, const void*, long unsigned int); TArgs = {const unsigned char* const&, const long unsigned int&}]’:
../src/catapult/crypto/Hashes.cpp:49:20:   required from ‘void catapult::crypto::{anonymous}::HashSingleBuffer(const EVP_MD*, const RawBuffer&, THash&) [with THash = catapult::utils::ByteArray<catapult::Hash160_tag>; EVP_MD = env_md_st; catapult::utils::RawBuffer = catapult::utils::BasicRawBuffer<const unsigned char>]’
../src/catapult/crypto/Hashes.cpp:55:53:   required from here
../src/catapult/crypto/OpensslContexts.h:44:22: error: cannot convert ‘evp_md_ctx_st*’ to ‘env_md_ctx_st*’ in argument passing
    auto result = func(get(), std::forward<TArgs>(args)...);
                  ~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../src/catapult/crypto/OpensslContexts.h:25:8: note: class type ‘evp_md_ctx_st’ is incomplete
 struct evp_md_ctx_st;
        ^~~~~~~~~~~~~
../src/catapult/crypto/OpensslContexts.h: In instantiation of ‘void catapult::crypto::OpensslDigestContext::dispatch(TFunc, TArgs&& ...) [with TFunc = int (*)(env_md_ctx_st*, unsigned char*, unsigned int*); TArgs = {unsigned char*, unsigned int*}]’:
../src/catapult/crypto/Hashes.cpp:50:4:   required from ‘void catapult::crypto::{anonymous}::HashSingleBuffer(const EVP_MD*, const RawBuffer&, THash&) [with THash = catapult::utils::ByteArray<catapult::Hash160_tag>; EVP_MD = env_md_st; catapult::utils::RawBuffer = catapult::utils::BasicRawBuffer<const unsigned char>]’
../src/catapult/crypto/Hashes.cpp:55:53:   required from here
../src/catapult/crypto/OpensslContexts.h:44:22: error: cannot convert ‘evp_md_ctx_st*’ to ‘env_md_ctx_st*’ in argument passing
    auto result = func(get(), std::forward<TArgs>(args)...);
                  ~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../src/catapult/crypto/OpensslContexts.h:25:8: note: class type ‘evp_md_ctx_st’ is incomplete
 struct evp_md_ctx_st;
        ^~~~~~~~~~~~~
../src/catapult/crypto/OpensslContexts.h: In instantiation of ‘void catapult::crypto::OpensslDigestContext::dispatch(TFunc, TArgs&& ...) [with TFunc = int (*)(env_md_ctx_st*, const env_md_st*, engine_st*); TArgs = {const env_md_st*, std::nullptr_t}]’:
../src/catapult/crypto/Hashes.cpp:109:3:   required from ‘catapult::crypto::HashBuilderT<TModeTag, THashTag>::HashBuilderT() [with TModeTag = catapult::crypto::Sha2ModeTag; THashTag = catapult::Hash512_tag]’
../src/catapult/crypto/Hashes.cpp:129:17:   required from here
../src/catapult/crypto/OpensslContexts.h:44:22: error: cannot convert ‘evp_md_ctx_st*’ to ‘env_md_ctx_st*’ in argument passing
    auto result = func(get(), std::forward<TArgs>(args)...);
                  ~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../src/catapult/crypto/OpensslContexts.h:25:8: note: class type ‘evp_md_ctx_st’ is incomplete
 struct evp_md_ctx_st;
        ^~~~~~~~~~~~~
[5/1851] Building CXX object src/catapult/crypto/CMakeFiles/catapult.crypto.dir/SharedKey.cpp.o
ninja: build stopped: subcommand failed.

DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=18.04
DISTRIB_CODENAME=bionic
DISTRIB_DESCRIPTION="Ubuntu 18.04.4 LTS"

Any help would be appreciated. Thank You.

**Comment by gimer** [comment]
hi, the docs don't mention this *yet*, we'll fix it:
 * **master** branch is generally considered _devel_ branch, and building instructions are almost never up to date with _master_ (that is until next release), moreover there's no guarantees whatsoever about state of _master_ branch
 * to build latest release, you need to checkout to given **tag** (as of now, that is v0.9.2.1)

**Comment by BIMTrazer** [comment]
Yes, release 0.9.2.1 worked.
Thank you.
