### ISSUE TITLE
IPv6 support

### ISSUE THREAD

**Issue by r3n3x** [nemtech/catapult-server#63]
May I propose to **enhance the Catapult Server project with IPv6 support**.
That can be helpful for spinning up large numbers of nodes, too. It's not easy (not affordable) to get a larger no. of IPv4 public IPs from the datacenter for my dedicated server. Different matter with IPv6.
[ I had started this NEM forum thread earlier: https://forum.nem.io/t/nem-symbol-ipv6-support/24559?u=r3n3 ]

**Comment by gimer** [comment]
@r3n3x just to let you know, this turned out to be more complicated, then we thought (we have no properly defined scenarios, how this should actually work - can explain details here or on slack if needed), so right now this is postponed

**Comment by r3n3x** [comment]
Thanks for the update on this issue @gimer ... Sure, please keep it view for later.

I am not actively following on Slack. NEM Forum or GitHub is good to provide more details and perhaps gather feedback, if you like.

Keep up the good work, guys!

**Comment by Jaguar0625** [comment]
Fixed in b6271132d.
