### ISSUE TITLE
A namespace cannot alias more than one asset

### ISSUE THREAD

**Issue by dgarcia360** [nemtech/catapult-server#65]
Originally reported on [Slack](https://nem2.slack.com/archives/CEZKUE4KB/p1586753790025500) by @David0817

**Problem**

It is possible to have a namespace aliasing more than one mosaic at the same time.

**Steps to reproduce the problem**

Given I have created 3 mosaics (A,B,C) and a namespace N.

1. Link N to A. 
2. Extend N duration.
3. Link N to B.
4. Extend N duration.
5. Link N to C.
6. Extend N duration.
7. Retrieve the aliases associated with A, B, and C. All the namespaces linked are N. 

The latest step is reproduced in this [gist](https://gist.github.com/dgarcia360/ce290070203832606d5c38d6c803729f).

**Comment by gimer** [comment]
> It is possible to have a namespace aliasing more than one mosaic at the same time.

no, mind that resolution happens on SERVER side as well, i.e. inside transfer tx, in case you'd have multiple entities aliasing the same namespace, what would alias inside of transaction mean?

**Comment by gimer** [comment]
I misread the question, this probably happen because of #66, and neither step 3 or 5 should be allowed when #66 is fixed

**Comment by Jaguar0625** [comment]
Fixed in e11b29c.
