### ISSUE TITLE
Extend a namespace duration removes its alias

### ISSUE THREAD

**Issue by dgarcia360** [nemtech/catapult-server#66]
**Problem**

Originally reported on [Slack](https://nem2.slack.com/archives/CEZKUE4KB/p1586753790025500) by @David0817

If an account decides to renew a namespace before it expires, the alias is lost. However, all the child subnamespaces keep the alias. 

Following the domain-namespace analogy, the domains DNS and data are preserved when this is renewed on time. In Symbol terms, the namespace link should be preserved too in the same situation. This will allow the user to not have to issue a new AliasTransaction, and the approach looks consistent with the current subnamespace alias behavior.

**Steps to reproduce the problem**

Given I have created a namespace N1, subnamespace N2, and two different mosaics (A, B).

1. Link N1 to A.
2. Link N2 to B.
3. Extend N1.
4. N1 was linking an account before the renewal, the link was lost: http://api-01.us-west-1.symboldev.network:3000/namespace/FFA2FA550DCC3CFC
5. N2 still links to B: http://api-01.us-west-1.symboldev.network:3000/namespace/85E63FD09D6087AC

**Comment by Jaguar0625** [comment]
Fixed in e11b29c.
