### ISSUE TITLE
Mosaic properties are not updated correctly.

### ISSUE THREAD

**Issue by Wayonb** [nemtech/catapult-server#69]
There are couple of issues with updating the flags:
1.  For the divisibility property xor operation is used but outcome does not look correct.  e.g. if current is 3 and updated in the notification is 3 then the updated divisibility value will be 0.  This is not what I would except as a user.  I would except either 3 or 6.
2. The update properties values are not check against the max config value. Below you see divisibility is 7 even though the max is configured for 6.

        model::MosaicProperties MergeProperties(
                const model::MosaicProperties& currentProperties,
                const model::MosaicProperties& notificationProperties,
                NotifyMode mode) {
            auto flags = Xor(currentProperties.flags(), notificationProperties.flags());
            auto divisibility = static_cast<uint8_t>(currentProperties.divisibility() ^ notificationProperties.divisibility());
            auto duration = NotifyMode::Commit == mode
                    ? currentProperties.duration() + notificationProperties.duration()
                    : currentProperties.duration() - notificationProperties.duration();
            return model::MosaicProperties(flags, divisibility, duration);
        }

```
[Switching to Thread 0x7ffecffff700 (LWP 44125)]
Thread 440 "5 transaction d" hit Breakpoint 1, catapult::observers::(anonymous namespace)::MergeProperties (currentProperties=..., notificationProperties=..., 
    mode=catapult::observers::NotifyMode::Commit)
    at ../plugins/txes/mosaic/src/observers/MosaicDefinitionObserver.cpp:35
35                auto flags = Xor(currentProperties.flags(), notificationProperties.flags());
(gdb) next
40                return model::MosaicProperties(flags, divisibility, duration);
(gdb) info locals
flags = catapult::model::MosaicFlags::None
divisibility = 7 '\a'
duration = {<catapult::utils::BasicBaseValue<unsigned long, catapult::BlockDuration_tag, catapult::utils::BaseValue<unsigned long, catapult::BlockDuration_tag> >> = {<catapult::BlockDuration_tag> = {<No data fields>}, m_value = {<catapult::utils::MoveOnly> = {<No data fields>}, 
      m_value = 10}}, <No data fields>}
(gdb) info args
currentProperties = @0x7ffecfffdbfc: {m_flags = catapult::model::MosaicFlags::Transferable, 
  m_divisibility = 4 '\004', 
  m_duration = {<catapult::utils::BasicBaseValue<unsigned long, catapult::BlockDuration_tag, catapult::utils::BaseValue<unsigned long, catapult::BlockDuration_tag> >> = {<catapult::BlockDuration_tag> = {<No data fields>}, m_value = {<catapult::utils::MoveOnly> = {<No data fields>}, 
        m_value = 5}}, <No data fields>}}
notificationProperties = @0x7ffecfffdfa0: {m_flags = catapult::model::MosaicFlags::Transferable, 
  m_divisibility = 3 '\003', 
  m_duration = {<catapult::utils::BasicBaseValue<unsigned long, catapult::BlockDuration_tag, catapult::utils::BaseValue<unsigned long, catapult::BlockDuration_tag> >> = {<catapult::BlockDuration_tag> = {<No data fields>}, m_value = {<catapult::utils::MoveOnly> = {<No data fields>}, 
        m_value = 5}}, <No data fields>}}
mode = catapult::observers::NotifyMode::Commit
```

**Comment by Jaguar0625** [comment]
Fixed in ac5add6c2cf97f064f7b80839d843c85d43c1644.
