### ISSUE TITLE
Boot error no private key file

### ISSUE THREAD

**Issue by BIMTrazer** [nemtech/catapult-server#70]
Greetings.

We are trying to run the new version (0.9.4.1) but now we see there is something different about th private boot key for the node, the parameter bootKey or privateKey in config-user.properties doesn't exist anymore.

Now it looks for a cert file inside certificate directory.

2020-05-06 20:22:05.703557 0x00007f784b35bac0: <error> (crypto::OpensslKeyUtils.cpp@61) Throwing exception: could not load private key from file (../certificate/ca.pubkey.pem) 
2020-05-06 20:22:05.703680 0x00007f784b35bac0: <fatal> (process::ProcessMain.cpp@64) 
thread: Process Main (s
unhandled exception while running local node!
../src/catapult/crypto/OpensslKeyUtils.cpp(61): Throw in function auto catapult::crypto::{anonymous}::TransformPemFileContents(const string&, TTransformer) [with TPemTraits = catapult::crypto::{anonymous}::PublicKeyPemTraits; TTransformer = std::pair<catapult::utils::ByteArray<catapult::Key_tag>, int> (*)(const evp_pkey_st&); std::string = std::__cxx11::basic_string<char>]
Dynamic exception type: boost::wrapexcept<catapult::catapult_error<std::invalid_argument> >
std::exception::what: could not load private key from file
[catapult::ErrorParam1*] = ../certificate/ca.pubkey.pem

How do you create this file?

Thank you.

**Comment by CrackTheCode016** [comment]
Hello,
The version as of this writing omits the `bootPrivateKey`, and instead specifies a self-signed x509, ed25519, TLS certificate for the node's identity.  You can specify where the server should look for these certificates  in `config-user.properties` via the `certificateDirectory` - I would suggest creating a `cert/` directory and pointing it there, where all keys / certificates will live.  

To generate the certificate, all the instructions are basically in these [comments](https://github.com/nemfoundation/symbol-testnet-bootstrap/blob/75f1c9cdda6e0c0926903595b5ca614470bbab8d/common/ruby/lib/symbol_utilities/cert_generate/crypto.rb#L88).  

Before running those commands, though, make sure you have the following ready: 

* OpenSSL 1.1.1 installed
* `ca.cnf` in your `certificateDirectory` (see below for example)
* `node.cnf` in your `certificateDirectory` (see below for example)

`ca.cnf` example:
```
[ca]
default_ca = CA_default

[CA_default]

dir = <certificateDirHere>
new_certs_dir = $dir/new_certs
database = $dir/index.txt
serial   = $dir/serial.dat

private_key = $dir/ca.key.pem
certificate = $dir/ca.cert.pem

policy = policy_catapult

[policy_catapult]
commonName              = supplied

[req]
prompt = no
distinguished_name = dn

[dn]
CN = some_name_here
```

`node.cnf` example:
```
[req]
prompt = no
distinguished_name = dn

[dn]
CN = some_name_here
```

If you have any trouble, let know.  Hope this helps!

**Comment by BIMTrazer** [comment]
Hi.
Thanks for your help! I was able to start the server.

**Comment by Jaguar0625** [comment]
Thanks for answering @CrackTheCode016!
