### ISSUE TITLE
Minimum importance required for a node to be considered as a synchronization partner should be configurable

### ISSUE THREAD

**Issue by Wayonb** [nemtech/catapult-server#71]
Unable to get time sync to work in testnet.  This is due to no nodes running meet the needs to be a synchronization partne node but the value is no configurable.

````
peer-node-0_1             | 2020-05-09 03:06:41.318547 0x00007f68affff700: <debug> (src::TimeSynchronizationUtils.cpp@68) timesync: number of selected nodes: 0 
peer-node-0_1             | 2020-05-09 03:06:41.318662 0x00007f68affff700: <debug> (src::TimeSynchronizationUtils.cpp@134) timesync: number of retrieved samples: 0
peer-node-0_1             | 2020-05-09 03:06:41.318694 0x00007f68affff700: <warning> (src::TimeSynchronizer.cpp@58) no synchronization samples available to calculate network time 
````

	/// Minimum importance a node must have in order to be considered as a synchronization partner.
	/// \note The value corresponds to having a vested balance of 1 NEM stake.
	constexpr double Required_Minimum_Importance = 0.00025;

**Comment by Jaguar0625** [comment]
Fixed in 142fff5.
