### ISSUE TITLE
New node is unable to sync the full chain in testnet

### ISSUE THREAD

**Issue by Wayonb** [nemtech/catapult-server#80]
A new node when trying to sync data from the testnet fails with an inconsistent state hash error.
http://api-01.us-west-1.096x.symboldev.network:3000/blocks/45856

``
api-node_1      | 2020-07-20 17:59:35.511757 0x00007f761bfff700: <info> (consumers::BlockChainProcessor.cpp@226) cache state hash (9 components) at height 45856
api-node_1      | D054CF03E97AAE08469C6C0373FB0B03BC3C5B95E17AFC9631ECF8DCE939C2E8
api-node_1      |  + 5FFA2BC2EE0AE13D2B8E213B9203AAA1E5A5F9F0BCDB69599DCC84E0C796B080
api-node_1      |  + 55E66B96E416A2F74FCBEE508CE5AF39016BBB831C9305E096970A6737DDB88E
api-node_1      |  + 645021003D8E16B7CF87A1A5F64F3AF6A303B5FC829D2E145AEE626BFB1935D8
api-node_1      |  + 22FBD6D21702BEAC2FA83C9710EE51A13E8657133AF3AE7D8A9F73A43F03D693
api-node_1      |  + 0000000000000000000000000000000000000000000000000000000000000000
api-node_1      |  + 0000000000000000000000000000000000000000000000000000000000000000
api-node_1      |  + 61A1034F46A9BE1201BD391225128402F8BD8C88C26BA518D5DF093EC7534D51
api-node_1      |  + 9D9E3C5152CE39BE3D59176F0764ED5004ADA8F8D48A6B87DA80D8F73E80C57D
api-node_1      |  + 3C6FE1491BC5AAE70D15315B5442C8A5BC1722CB65F5F9089366488488D843BD 
api-node_1      | 2020-07-20 17:59:35.511783 0x00007f761bfff700: <warning> (consumers::BlockChainSyncConsumer.cpp@246) processing of peer chain failed with Failure_Chain_Block_Inconsistent_State_Hash 
api-node_1      | 2020-07-20 17:59:35.519808 0x00007f761b7fe700: <info> (disruptor::ConsumerDispatcher.cpp@43) completing processing of element 129 (400 blocks (heights 45602 - 46001) [78216E2F] from Remote_Pull), last consumer is 0 elements behind 
api-node_1      | 2020-07-20 17:59:35.519860 0x00007f761b7fe700: <warning> (consumers::ReclaimMemoryInspector.cpp@32) consumer aborted at position 128 while processing 400 blocks (heights 45602 - 46001) [78216E2F] from Remote_Pull due to Failure_Chain_Block_Inconsistent_State_Hash 
``

**Comment by Jaguar0625** [comment]
Fixed in 81f68d6d5 (0.9.6.4).
