### ISSUE TITLE
In v0.9.6.3-beta1, once bootstrap is stopped and restarted block height does not progress from "47356"

### ISSUE THREAD

**Issue by dusanjp** [nemtech/catapult-server#81]
In v0.9.6.3-beta1, once bootstrap is stopped and restarted
block height does not progress from "47356"

This issue occurs in multiple people, multiple environments

If the v0.9.6.3-beta1 node that is running now is stopped even once and then restarted
When you point at 47356, the block height stops.

**Comment by dusanjp** [comment]
We request prompt analysis of this problem, resolution, and announcement of a new ver.

**Comment by Jaguar0625** [comment]
Fixed in 81f68d6d5 (0.9.6.4).
