### ISSUE TITLE
Store resolved addresses to the mongodb transaction collection on confirmation time

### ISSUE THREAD

**Issue by Vektrat** [nemtech/catapult-server#82]
Context: https://github.com/nemtech/catapult-rest/issues/436#issuecomment-664958359

it'd be helpful to have information on what address an alias was resolving to at transaction confirmation time in order to make queries by address to the mongodb complete (rather than missing entities that store just the alias)

as mentioned earlier `meta.addresses` looks like a good candidate for this, but feel free to choose whatever suits you best

note that this is only possible for the (confirmed) `transactions` collection

**Comment by Jaguar0625** [comment]
Fixed in 88aa56fe1.
