### ISSUE TITLE
Nemesis transactions are confirmed when signed with an invalid generation hash

### ISSUE THREAD

**Issue by fboucquez** [nemtech/catapult-server#85]
During my opt-in tests, I've noticed that transactions singed with a different nemesisGenerationHashSeed can be put in `transactionsDirectory`. Nemgen NOR the peers are complaining about them. The transactions end up confirmed on block 1. If you announce a transaction after block 1, they are rejected with a `Failure_Consumer_Batch_Signature_Not_Verifiable` error.

Is this an issue? Should these transactions be rejected? What are the secondary effects of having transactions signed with the incorrect generation hash seed? Could affect other parts of the system? Maybe receipts, hashes or Merkple proof are affected? 

If this is not an issue, Wallets' NIS1 optin module can pretty much use any generation hash seed when signing namespaces, VRF and multisig transactions. The different generation hash would be ignored on nemesis.

@Jaguar0625 @Wayonb @gimer

**Comment by Jaguar0625** [comment]
We should probably validate transactions in nemesis block. Previously we assumed the creator of the nemesis block would not intentionally insert bad transactions.

NIS1 optin module should use symbol network generation hash.

**Comment by fboucquez** [comment]
Thanks!

Have you guys defined the generation hash seed for the main net? We need to provide it before the nis1 wallet opt-in release.

**Comment by gimer** [comment]
gh seed `57F7DA205008026C776CB6AED843393F04CD458E0AA2D9F1D5F31A402072B2D6`

**Comment by Jaguar0625** [comment]
Fixed in cd5438a.
