### ISSUE TITLE
Announce metadataTransactions with same metadata value

### ISSUE THREAD

**Issue by rg911** [nemtech/catapult-server#87]
I tried to announce 2 metadata transactions with the same metadata value. 

1.  value: `test`,  delta: 4
2. value: `test`, delta: 0

Both get announced okay without error, but the final value is empty (or the xor value).

The question is if the second metadata transaction announced with the exact same value but not xor value, should we expect the metadata value stays the same as the previous one?

**Comment by fboucquez** [comment]
Would it be possible to generate a vector test around metadata? Something like original value, new value, delta, xor value?

**Comment by Jaguar0625** [comment]
@rg911 - please provide repro steps

Specifically for each transaction please fill in the following information:
1. Initial State
1. Transaction Contents
1. Actual Result
1. Expected Result

**Comment by rg911** [comment]
1. A brand new account without any metadata created before. 
2. Create 2 account metadata transactions against the above account

first transaction
``` js
AccountMetadataTransaction.create(
  Deadline.create(),
  account.address,
  UInt64.fromUint(6), // metadata key
  23, // value size delta
  'Test account meta value', // value
  networkType,
 maxFee,
);
```
second transaction
``` js
AccountMetadataTransaction.create(
  Deadline.create(),
  account.address,
  UInt64.fromUint(6), // metadata key
  0, // value size delta
  'Test account meta value', // value
  networkType,
 maxFee,
);
```
3. Both transactions get announced successfully. 
first transaction creates metadata:
``` json
"metadataEntry": {
  "compositeHash": "3DA8498077CBDDB166BE498FD0025C2C3FA38E2D6092D120BA3FA25F9F5CDEB0",
  "sourceAddress": "98B7E6511641DB30173025B0C21E6BAF23CADC60FA94CF27",
  "targetAddress": "98B7E6511641DB30173025B0C21E6BAF23CADC60FA94CF27",
  "scopedMetadataKey": "0000000000000006",
  "targetId": "0000000000000000",
  "metadataType": 0,
  "valueSize": 23,
  "value": "54657374206163636F756E74206D6574612076616C7565"
}
```

then the second transaction updates the metadata:
``` json
"metadataEntry": {
  "compositeHash": "3DA8498077CBDDB166BE498FD0025C2C3FA38E2D6092D120BA3FA25F9F5CDEB0",
  "sourceAddress": "98B7E6511641DB30173025B0C21E6BAF23CADC60FA94CF27",
  "targetAddress": "98B7E6511641DB30173025B0C21E6BAF23CADC60FA94CF27",
  "scopedMetadataKey": "0000000000000006",
  "targetId": "0000000000000000",
  "metadataType": 0,
  "valueSize": 23,
  "value": "0000000000000000000000000000000000000000000000"
}
```
4. Should the expected metadata value of the second transaction to stay as the first one?

**Comment by Jaguar0625** [comment]
The update operation applies an XOR. Any value XOR'd by itself is 0, so
`54657374206163636F756E74206D6574612076616C7565 ^ 54657374206163636F756E74206D6574612076616C7565 == 0000000000000000000000000000000000000000000000`
