### ISSUE TITLE
TRANSFER and MOSAIC_DEFINITION mismatching transaction  hash 

### ISSUE THREAD

**Issue by fboucquez** [nemtech/catapult-server#88]
I'm running some integration tests, testing that all the hashed returned in the completed transactions matches the ones the SDKs generate. I've noticed that Transfer and Mosaic Definition differ on Block 1.

I'm using 0.9.7 [symbol bootstrap](https://github.com/nemtech/symbol-bootstrap/tree/970_changes) and the [Java SDK](https://github.com/nemtech/symbol-sdk-java/blob/main/sdk-core/src/main/java/io/nem/symbol/sdk/model/transaction/Transaction.java#L168).  The Typescript SDK has the same issue.

The odd part is that some transactions' hashes don't match

Generation Hash: A23BACAA2B883416C1E8C9916B473E27AA945D9211789757EB6E05B8E9235FCA

Some examples of my run:

| Valid | Type | Height | Stored Hash | Calculated Hash | Binary | Json | 
| --------- | --------- | --------- | --------- | --------- | --------- | --------- | 
| :x: | TRANSFER | 1 | 6E1D88891ECD9407E1EFD7C34BAA648B7ABA50F0B5DA2D270AEBEB4A12D9215B | A3BC195A81D5AC6D661ABA4A3E16B11E785EB0E51ADCCC0B6040B53DA511C349 | B1000000000000000FC442FCC4BE564202A61893F3066E16A4A0D4E007706C4903F901D78BCBE3FF1D6D44DB5BAEF09F1A66376394B5A3858E5839EFE16FFFEBF6B188DB53FAB905195F5DC03351D77168854F227B0E51A4EB9FDCFB96CC4A07D4BFD42303835B61000000000198544100000000000000000100000000000000983C69FDCC14C893CCC71C706B23BCBF81869CA1AE9C790D010001000000000044B262C46CEABB8574C72385D963010000 | {"id":"5F5FEE28AA109E74704A9C27","meta":{"height":"1","hash":"6E1D88891ECD9407E1EFD7C34BAA648B7ABA50F0B5DA2D270AEBEB4A12D9215B","merkleComponentHash":"6E1D88891ECD9407E1EFD7C34BAA648B7ABA50F0B5DA2D270AEBEB4A12D9215B","index":15},"transaction":{"size":176,"signature":"0FC442FCC4BE564202A61893F3066E16A4A0D4E007706C4903F901D78BCBE3FF1D6D44DB5BAEF09F1A66376394B5A3858E5839EFE16FFFEBF6B188DB53FAB905","signerPublicKey":"195F5DC03351D77168854F227B0E51A4EB9FDCFB96CC4A07D4BFD42303835B61","version":1,"network":152,"type":16724,"maxFee":"0","deadline":"1","recipientAddress":"983C69FDCC14C893CCC71C706B23BCBF81869CA1AE9C790D","mosaics":[{"id":"85BBEA6CC462B244","amount":"391260869478260"}],"message":{"type":0}}} |
| :heavy_check_mark: | NAMESPACE_REGISTRATION | 1 | 634C966FF9B3A954B4DB0F30956EEE3A305E07D69F2C93B6C9A18710D778A3F8 | 634C966FF9B3A954B4DB0F30956EEE3A305E07D69F2C93B6C9A18710D778A3F8 | 9500000000000000631DE8F6383866886216F0D296FFBF600C750589B43CF7C8C832C6C8211BBB49EAB15E0BD56CE65071809DF2C62AD1CEA79491FFB1CDD8D9488C7613EF46070A195F5DC03351D77168854F227B0E51A4EB9FDCFB96CC4A07D4BFD42303835B610000000001984E410000000000000000010000000000000000000000000000004F1B65BA5F7F49B10003636174 | {"id":"5F5FEE28AA109E74704A9C28","meta":{"height":"1","hash":"634C966FF9B3A954B4DB0F30956EEE3A305E07D69F2C93B6C9A18710D778A3F8","merkleComponentHash":"634C966FF9B3A954B4DB0F30956EEE3A305E07D69F2C93B6C9A18710D778A3F8","index":0},"transaction":{"size":149,"signature":"631DE8F6383866886216F0D296FFBF600C750589B43CF7C8C832C6C8211BBB49EAB15E0BD56CE65071809DF2C62AD1CEA79491FFB1CDD8D9488C7613EF46070A","signerPublicKey":"195F5DC03351D77168854F227B0E51A4EB9FDCFB96CC4A07D4BFD42303835B61","version":1,"network":152,"type":16718,"maxFee":"0","deadline":"1","duration":"0","id":"B1497F5FBA651B4F","registrationType":0,"name":"cat"}} |
| :heavy_check_mark: | MOSAIC_SUPPLY_CHANGE | 1 | 09976BC158F881B65DACABFA737B5C1ED2AFE3BBC62B58D9B0BB232B0F544090 | 09976BC158F881B65DACABFA737B5C1ED2AFE3BBC62B58D9B0BB232B0F544090 | 91000000000000009ACF45A99A04878DD253C6F88DB1F12592EDE43C28633A8FEFA1AE22E74DB3A11F09391B8DA271E9649747DE5FE853880E52B4CD103758C69569784CD41FA706195F5DC03351D77168854F227B0E51A4EB9FDCFB96CC4A07D4BFD42303835B610000000001984D420000000000000000010000000000000044B262C46CEABB8580EB36F68AF81F0001 | {"id":"5F5FEE28AA109E74704A9C2B","meta":{"height":"1","hash":"09976BC158F881B65DACABFA737B5C1ED2AFE3BBC62B58D9B0BB232B0F544090","merkleComponentHash":"09976BC158F881B65DACABFA737B5C1ED2AFE3BBC62B58D9B0BB232B0F544090","index":5},"transaction":{"size":145,"signature":"9ACF45A99A04878DD253C6F88DB1F12592EDE43C28633A8FEFA1AE22E74DB3A11F09391B8DA271E9649747DE5FE853880E52B4CD103758C69569784CD41FA706","signerPublicKey":"195F5DC03351D77168854F227B0E51A4EB9FDCFB96CC4A07D4BFD42303835B61","version":1,"network":152,"type":16973,"maxFee":"0","deadline":"1","mosaicId":"85BBEA6CC462B244","delta":"8998999998000000","action":1}} |
| :x: | MOSAIC_DEFINITION | 1 | D325B9F426C7CEECCB4CDF5C2225730995599222D8F3E4E76D7A9103A9020E9D | E835A569B8C3CB263B0DF64DFC9498CD81D201C8158477A4C2A01472F1C25A90 | 96000000000000000D12C3AD8B22F1300FDD9422563662D09B7AD95C4885CFF4BB77931109AA79A834F7292C06DA476B6FA1CB239FA5ABCB946AEA9CD92EF1FAD54D4F2B08F1F90C195F5DC03351D77168854F227B0E51A4EB9FDCFB96CC4A07D4BFD42303835B610000000001984D41000000000000000001000000000000007A9039145F98733E0000000000000000000000010303 | {"id":"5F5FEE28AA109E74704A9C2E","meta":{"height":"1","hash":"D325B9F426C7CEECCB4CDF5C2225730995599222D8F3E4E76D7A9103A9020E9D","merkleComponentHash":"D325B9F426C7CEECCB4CDF5C2225730995599222D8F3E4E76D7A9103A9020E9D","index":6},"transaction":{"size":150,"signature":"0D12C3AD8B22F1300FDD9422563662D09B7AD95C4885CFF4BB77931109AA79A834F7292C06DA476B6FA1CB239FA5ABCB946AEA9CD92EF1FAD54D4F2B08F1F90C","signerPublicKey":"195F5DC03351D77168854F227B0E51A4EB9FDCFB96CC4A07D4BFD42303835B61","version":1,"network":152,"type":16717,"maxFee":"0","deadline":"1","id":"3E73985F1439907A","duration":"0","nonce":16777216,"flags":3,"divisibility":3}} |
| :heavy_check_mark: | MOSAIC_ALIAS | 1 | 170F85547AB5D50DDA05856461D6D6934774A9477A7808725E122DE7E4DC425F | 170F85547AB5D50DDA05856461D6D6934774A9477A7808725E122DE7E4DC425F | 9100000000000000CAD3D9B6D1641B767272B44AB35EA393B40FED4B4FB07D5F9F794D99056595FED6C6545557DEB719690E883CE47786770FD5D7990107C919C4657450F0470B01195F5DC03351D77168854F227B0E51A4EB9FDCFB96CC4A07D4BFD42303835B610000000001984E43000000000000000001000000000000001C29E1B7B29912947A9039145F98733E01 | {"id":"5F5FEE28AA109E74704A9C33","meta":{"height":"1","hash":"170F85547AB5D50DDA05856461D6D6934774A9477A7808725E122DE7E4DC425F","merkleComponentHash":"170F85547AB5D50DDA05856461D6D6934774A9477A7808725E122DE7E4DC425F","index":7},"transaction":{"size":145,"signature":"CAD3D9B6D1641B767272B44AB35EA393B40FED4B4FB07D5F9F794D99056595FED6C6545557DEB719690E883CE47786770FD5D7990107C919C4657450F0470B01","signerPublicKey":"195F5DC03351D77168854F227B0E51A4EB9FDCFB96CC4A07D4BFD42303835B61","version":1,"network":152,"type":17230,"maxFee":"0","deadline":"1","namespaceId":"941299B2B7E1291C","mosaicId":"3E73985F1439907A","aliasAction":1}} |
| :heavy_check_mark: | MOSAIC_DEFINITION | 1 | 2AA536F34141197669A3DBAE1FCB616B07ABFE6757354CC985015AE19C3A6414 | 2AA536F34141197669A3DBAE1FCB616B07ABFE6757354CC985015AE19C3A6414 | 960000000000000013E61202CB13F0A4F37A0326C06FA46A1BC7691BF7C75A145AB495BB699BE4F9BBA0121CE893018B20220D3BAE0BB5DCE60ED4FD16F175D543ADD6330950DD05195F5DC03351D77168854F227B0E51A4EB9FDCFB96CC4A07D4BFD42303835B610000000001984D4100000000000000000100000000000000D824A2941C5071580000000000000000000000000206 | {"id":"5F5FEE28AA109E74704A9C37","meta":{"height":"1","hash":"2AA536F34141197669A3DBAE1FCB616B07ABFE6757354CC985015AE19C3A6414","merkleComponentHash":"2AA536F34141197669A3DBAE1FCB616B07ABFE6757354CC985015AE19C3A6414","index":3},"transaction":{"size":150,"signature":"13E61202CB13F0A4F37A0326C06FA46A1BC7691BF7C75A145AB495BB699BE4F9BBA0121CE893018B20220D3BAE0BB5DCE60ED4FD16F175D543ADD6330950DD05","signerPublicKey":"195F5DC03351D77168854F227B0E51A4EB9FDCFB96CC4A07D4BFD42303835B61","version":1,"network":152,"type":16717,"maxFee":"0","deadline":"1","id":"5871501C94A224D8","duration":"0","nonce":0,"flags":2,"divisibility":6}} |
| :heavy_check_mark: | VOTING_KEY_LINK | 1 | 882D500ADD326DD269845984CA84C452CCD9D01929D6A4D7D179936769576409 | 882D500ADD326DD269845984CA84C452CCD9D01929D6A4D7D179936769576409 | B9000000000000006F6EAA8C3267058DE7C92EF280198A2178C9A5499EF9DA69B8DE9BA1D4556F5B3155904491BE14EFB9D524F03768AD84848D771EF0D692F1D051402328F9470683C00CE9E996C3ACC4EF505DE14022057C69F0E1FAA223667DD8628CF54D15B1000000000198434100000000000000000100000000000000F3AF8192E08C161F04F825F3548EC0C07E2BE124A10E7E8D7B4BF685A44DE5D70000000000000000000000000000000001000000A866000001 | {"id":"5F5FEE28AA109E74704A9C45","meta":{"height":"1","hash":"882D500ADD326DD269845984CA84C452CCD9D01929D6A4D7D179936769576409","merkleComponentHash":"882D500ADD326DD269845984CA84C452CCD9D01929D6A4D7D179936769576409","index":35},"transaction":{"size":185,"signature":"6F6EAA8C3267058DE7C92EF280198A2178C9A5499EF9DA69B8DE9BA1D4556F5B3155904491BE14EFB9D524F03768AD84848D771EF0D692F1D051402328F94706","signerPublicKey":"83C00CE9E996C3ACC4EF505DE14022057C69F0E1FAA223667DD8628CF54D15B1","version":1,"network":152,"type":16707,"maxFee":"0","deadline":"1","linkedPublicKey":"F3AF8192E08C161F04F825F3548EC0C07E2BE124A10E7E8D7B4BF685A44DE5D700000000000000000000000000000000","startEpoch":1,"endEpoch":26280,"linkAction":1}} |
| :heavy_check_mark: | VRF_KEY_LINK | 1 | F9F7E2D210D89A8050CD5009A1B7F30C53DFDFF8DD54524944EECF1DCABAA1A7 | F9F7E2D210D89A8050CD5009A1B7F30C53DFDFF8DD54524944EECF1DCABAA1A7 | A1000000000000004FEB08057F6289293D3114BB2B0B3475ECF284800FDD37181A31D7F9C3FA9481584FE049B37C5097E364E894A5CEC1D469A9EA0FD694D933A893E707311E510114D96DE8081C3AA4E3A0B78A0D2603668B1680532BB3F9F3E93CAE343C9DD09B0000000001984342000000000000000001000000000000006F5C7F2C0F53C023B5A9E2D054AE84FD899C577B14284E94069D1F7DD73CAA6F01 | {"id":"5F5FEE28AA109E74704A9C4A","meta":{"height":"1","hash":"F9F7E2D210D89A8050CD5009A1B7F30C53DFDFF8DD54524944EECF1DCABAA1A7","merkleComponentHash":"F9F7E2D210D89A8050CD5009A1B7F30C53DFDFF8DD54524944EECF1DCABAA1A7","index":37},"transaction":{"size":161,"signature":"4FEB08057F6289293D3114BB2B0B3475ECF284800FDD37181A31D7F9C3FA9481584FE049B37C5097E364E894A5CEC1D469A9EA0FD694D933A893E707311E5101","signerPublicKey":"14D96DE8081C3AA4E3A0B78A0D2603668B1680532BB3F9F3E93CAE343C9DD09B","version":1,"network":152,"type":16963,"maxFee":"0","deadline":"1","linkedPublicKey":"6F5C7F2C0F53C023B5A9E2D054AE84FD899C577B14284E94069D1F7DD73CAA6F","linkAction":1}} |
| :heavy_check_mark: | TRANSFER | 5 | 46EAF2C7B3D7BA3169105AD14E27348A73C6ED7C04A2EC51FBCAF45639384969 | 46EAF2C7B3D7BA3169105AD14E27348A73C6ED7C04A2EC51FBCAF45639384969 | CA000000000000008B54ACF50203A650129B6199CA45123141E837E2AF710E4A7770763D6A9DD26D66DF8DD132964AEB5A286E72FCAB282504C666D8027E15CE16EE6CDADA102101DB0E3BCEC639C180DC5A38C12346F51CCA93E01556341F14173ED49851A20F94000000000198544140420F000000000094E76637060000009802F51D156B5E8B6D9A70509E46522BA24FB91D39E80A5F1A00010000000000D824A2941C50715800E1F5050000000000453245546573743A53657455704163636F756E7473546F6F6C | {"id":"5F5FEE86AA109E74704A9C5A","meta":{"height":"5","hash":"46EAF2C7B3D7BA3169105AD14E27348A73C6ED7C04A2EC51FBCAF45639384969","merkleComponentHash":"46EAF2C7B3D7BA3169105AD14E27348A73C6ED7C04A2EC51FBCAF45639384969","index":0},"transaction":{"size":202,"signature":"8B54ACF50203A650129B6199CA45123141E837E2AF710E4A7770763D6A9DD26D66DF8DD132964AEB5A286E72FCAB282504C666D8027E15CE16EE6CDADA102101","signerPublicKey":"DB0E3BCEC639C180DC5A38C12346F51CCA93E01556341F14173ED49851A20F94","version":1,"network":152,"type":16724,"maxFee":"1000000","deadline":"26699294612","recipientAddress":"9802F51D156B5E8B6D9A70509E46522BA24FB91D39E80A5F","mosaics":[{"id":"5871501C94A224D8","amount":"100000000"}],"message":{"type":0,"payload":"453245546573743A53657455704163636F756E7473546F6F6C"}}} |
| :heavy_check_mark: | HASH_LOCK | 22 | 6D8D48DB5DDCE6680B028F1F1C94E2796AF872E0765B3F2B3026516A4B80AE3D | 6D8D48DB5DDCE6680B028F1F1C94E2796AF872E0765B3F2B3026516A4B80AE3D | B800000000000000765D301756B4BB772F5A88ED6999BF21FAEC10B30B3905AD518CA56D38642790AE1CA4A7B25C4C5E582B1890E4638B0DDB773D7F3B3EC006502971914F214504BDE86E53FC0CBDE08A27B059A86F92E2F99F85711E7615A74FDA8608683F8D5F000000000198484140420F0000000000F4306A3706000000D824A2941C50715880969800000000006400000000000000ADE606F3EC56FC7D8D25A96CF6CEE5DDA19EE9F0EF3B76E50F123370FCB5042A | {"id":"5F5FEF67AA109E74704A9CC1","meta":{"height":"22","hash":"6D8D48DB5DDCE6680B028F1F1C94E2796AF872E0765B3F2B3026516A4B80AE3D","merkleComponentHash":"6D8D48DB5DDCE6680B028F1F1C94E2796AF872E0765B3F2B3026516A4B80AE3D","index":1},"transaction":{"size":184,"signature":"765D301756B4BB772F5A88ED6999BF21FAEC10B30B3905AD518CA56D38642790AE1CA4A7B25C4C5E582B1890E4638B0DDB773D7F3B3EC006502971914F214504","signerPublicKey":"BDE86E53FC0CBDE08A27B059A86F92E2F99F85711E7615A74FDA8608683F8D5F","version":1,"network":152,"type":16712,"maxFee":"1000000","deadline":"26699510004","mosaicId":"5871501C94A224D8","amount":"10000000","duration":"100","hash":"ADE606F3EC56FC7D8D25A96CF6CEE5DDA19EE9F0EF3B76E50F123370FCB5042A"}} |
| :heavy_check_mark: | MOSAIC_DEFINITION | 22 | 221449019013435BB70A2533AB1F9BCCFCBBC3FD3FB6CF41D898EDB5059046FE | 221449019013435BB70A2533AB1F9BCCFCBBC3FD3FB6CF41D898EDB5059046FE | 9600000000000000E81E6D28A853E3FEB374B1CEB034F70956E5732ABA6FD47C184ABC4332CB5F85C4BF43CA744E4AE53A1A3276B498C0D809ED8DA3A996489B36819E22E5BC370CDB0E3BCEC639C180DC5A38C12346F51CCA93E01556341F14173ED49851A20F940000000001984D4140420F0000000000684C6A370600000050B87D39456FE276640000000000000013197DF90704 | {"id":"5F5FEF67AA109E74704A9CC2","meta":{"height":"22","hash":"221449019013435BB70A2533AB1F9BCCFCBBC3FD3FB6CF41D898EDB5059046FE","merkleComponentHash":"221449019013435BB70A2533AB1F9BCCFCBBC3FD3FB6CF41D898EDB5059046FE","index":0},"transaction":{"size":150,"signature":"E81E6D28A853E3FEB374B1CEB034F70956E5732ABA6FD47C184ABC4332CB5F85C4BF43CA744E4AE53A1A3276B498C0D809ED8DA3A996489B36819E22E5BC370C","signerPublicKey":"DB0E3BCEC639C180DC5A38C12346F51CCA93E01556341F14173ED49851A20F94","version":1,"network":152,"type":16717,"maxFee":"1000000","deadline":"26699517032","id":"76E26F45397DB850","duration":"100","nonce":4185725203,"flags":7,"divisibility":4}} |
| :heavy_check_mark: | NAMESPACE_REGISTRATION | 23 | 4AFDFC3F51ECAF7FD5124F7B15ED5AEEE30BA954CB07295DA702BB7C8264C8C9 | 4AFDFC3F51ECAF7FD5124F7B15ED5AEEE30BA954CB07295DA702BB7C8264C8C9 | CF00000000000000810D3F1A8419E6287ACDE96A4B55FA35C9E503161AC52BB0665D1A45B3AD9E4A14D3218833270E191FDA0E3CE8256BEF761BD8D48FA9D045CBEB4152D096030FDB0E3BCEC639C180DC5A38C12346F51CCA93E01556341F14173ED49851A20F940000000001984E4140420F000000000027776A37060000000A000000000000007A17421624490CB3003D6D6F736169637265737472696374696F6E7365727669636569745F6372656174656D6F73616963676C6F62616C7265737472696374696F6E3132383330 | {"id":"5F5FEF76AA109E74704A9CCE","meta":{"height":"23","hash":"4AFDFC3F51ECAF7FD5124F7B15ED5AEEE30BA954CB07295DA702BB7C8264C8C9","merkleComponentHash":"4AFDFC3F51ECAF7FD5124F7B15ED5AEEE30BA954CB07295DA702BB7C8264C8C9","index":0},"transaction":{"size":207,"signature":"810D3F1A8419E6287ACDE96A4B55FA35C9E503161AC52BB0665D1A45B3AD9E4A14D3218833270E191FDA0E3CE8256BEF761BD8D48FA9D045CBEB4152D096030F","signerPublicKey":"DB0E3BCEC639C180DC5A38C12346F51CCA93E01556341F14173ED49851A20F94","version":1,"network":152,"type":16718,"maxFee":"1000000","deadline":"26699527975","duration":"10","id":"B30C49241642177A","registrationType":0,"name":"mosaicrestrictionserviceit_createmosaicglobalrestriction12830"}} |
| :heavy_check_mark: | AGGREGATE_COMPLETE | 14 | 86501B7892400E9F450297F889891A9FEEFBB97FE9F9989EC5FB233C27A9EEE8 | 86501B7892400E9F450297F889891A9FEEFBB97FE9F9989EC5FB233C27A9EEE8 | 00010000000000001891AB154260966313308E0EB19CDD17CBBCC8E6C316C128032BDAF7CCF3F3D5AC6D5B8EE07485E56BA0DA31D44243840659A4164866D6A1336B469A3EB7970EDB0E3BCEC639C180DC5A38C12346F51CCA93E01556341F14173ED49851A20F94000000000198414140420F00000000009888683706000000E4A02E0339FEF1FE48CD1900E9EF4AB770D3FE336056FAF5A595EF57A34B1A0258000000000000005500000000000000DB0E3BCEC639C180DC5A38C12346F51CCA93E01556341F14173ED49851A20F940000000001984E4164000000000000004BC1046F8821B0AD0013636F7369676E61746F72792D6163636F756E74000000 | {"id":"5F5FEEF8AA109E74704A9C8D","meta":{"height":"14","hash":"86501B7892400E9F450297F889891A9FEEFBB97FE9F9989EC5FB233C27A9EEE8","merkleComponentHash":"86501B7892400E9F450297F889891A9FEEFBB97FE9F9989EC5FB233C27A9EEE8","index":0},"transaction":{"size":256,"signature":"1891AB154260966313308E0EB19CDD17CBBCC8E6C316C128032BDAF7CCF3F3D5AC6D5B8EE07485E56BA0DA31D44243840659A4164866D6A1336B469A3EB7970E","signerPublicKey":"DB0E3BCEC639C180DC5A38C12346F51CCA93E01556341F14173ED49851A20F94","version":1,"network":152,"type":16705,"maxFee":"1000000","deadline":"26699401368","transactionsHash":"E4A02E0339FEF1FE48CD1900E9EF4AB770D3FE336056FAF5A595EF57A34B1A02","transactions":[{"id":"5F5FEEF8AA109E74704A9C8E","meta":{"height":"14","aggregateHash":"86501B7892400E9F450297F889891A9FEEFBB97FE9F9989EC5FB233C27A9EEE8","aggregateId":"5F5FEEF8AA109E74704A9C8D","index":0},"transaction":{"signerPublicKey":"DB0E3BCEC639C180DC5A38C12346F51CCA93E01556341F14173ED49851A20F94","version":1,"network":152,"type":16718,"duration":"100","id":"ADB021886F04C14B","registrationType":0,"name":"cosignatory-account"}}]}} |
| :heavy_check_mark: | AGGREGATE_BONDED | 23 | ADE606F3EC56FC7D8D25A96CF6CEE5DDA19EE9F0EF3B76E50F123370FCB5042A | ADE606F3EC56FC7D8D25A96CF6CEE5DDA19EE9F0EF3B76E50F123370FCB5042A | E0010000000000002A00A593F8AA76382B97CB1C33EFC09E78499C2C2A774399F048B973BC832F1E2298A11C02972DF539A88C5A45B786E27949D4CC49A462334FED349A6950BA00BDE86E53FC0CBDE08A27B059A86F92E2F99F85711E7615A74FDA8608683F8D5F000000000198414240420F0000000000F2306A3706000000928CD4E4C79C343DB9E32CB1DA346B3267ABD9DC59DAA09F635111F6F21B16C668000000000000006800000000000000BDE86E53FC0CBDE08A27B059A86F92E2F99F85711E7615A74FDA8608683F8D5F000000000198554101010200000000009810C2CDD90D5F69D40CC7CEF66A7A71DFEDC08A4269BEDE98CFBB2360B8729830A8EDDF3B44019DAA41C7BC1B26700700000000000000004E804DF9E11A41933021D0EEBD6315EA50E3401AB6CCFDC127241C7A4F0A0915252B89ED086E78BFC602326611FD078D4F752322A2FF8E114A74871AFD3B8A541405086AF7B6806954162A9545D7E82950D37082F76DE7ACD97739681F2E47040000000000000000683E9981213B9682CFD442FAF9808C47B163839B22AEB7C9346C1373EFBE5912867603E0BC7B346B4AE7DDDEE3D3446432A1499544319122D35B470FE414ABD0D77AA18C5E66D222FBBB52636147AE1F955B6829471E520FEF5D24788E6CFB07 | {"id":"5F5FEF76AA109E74704A9CD1","meta":{"height":"23","hash":"ADE606F3EC56FC7D8D25A96CF6CEE5DDA19EE9F0EF3B76E50F123370FCB5042A","merkleComponentHash":"576EB263335F4C33F77A0260C575A2D8C1F4E26AD05722A4722024876FDB06F0","index":2},"transaction":{"size":480,"signature":"2A00A593F8AA76382B97CB1C33EFC09E78499C2C2A774399F048B973BC832F1E2298A11C02972DF539A88C5A45B786E27949D4CC49A462334FED349A6950BA00","signerPublicKey":"BDE86E53FC0CBDE08A27B059A86F92E2F99F85711E7615A74FDA8608683F8D5F","version":1,"network":152,"type":16961,"maxFee":"1000000","deadline":"26699510002","transactionsHash":"928CD4E4C79C343DB9E32CB1DA346B3267ABD9DC59DAA09F635111F6F21B16C6","cosignatures":[{"signature":"252B89ED086E78BFC602326611FD078D4F752322A2FF8E114A74871AFD3B8A541405086AF7B6806954162A9545D7E82950D37082F76DE7ACD97739681F2E4704","version":"0","signerPublicKey":"4E804DF9E11A41933021D0EEBD6315EA50E3401AB6CCFDC127241C7A4F0A0915"},{"signature":"867603E0BC7B346B4AE7DDDEE3D3446432A1499544319122D35B470FE414ABD0D77AA18C5E66D222FBBB52636147AE1F955B6829471E520FEF5D24788E6CFB07","version":"0","signerPublicKey":"683E9981213B9682CFD442FAF9808C47B163839B22AEB7C9346C1373EFBE5912"}],"transactions":[{"id":"5F5FEF76AA109E74704A9CD2","meta":{"height":"23","aggregateHash":"ADE606F3EC56FC7D8D25A96CF6CEE5DDA19EE9F0EF3B76E50F123370FCB5042A","aggregateId":"5F5FEF76AA109E74704A9CD1","index":0},"transaction":{"signerPublicKey":"BDE86E53FC0CBDE08A27B059A86F92E2F99F85711E7615A74FDA8608683F8D5F","version":1,"network":152,"type":16725,"minRemovalDelta":1,"minApprovalDelta":1,"addressAdditions":["9810C2CDD90D5F69D40CC7CEF66A7A71DFEDC08A4269BEDE","98CFBB2360B8729830A8EDDF3B44019DAA41C7BC1B267007"]}}]}} |

**Comment by fboucquez** [comment]
I've noticed that the 0 block transfer transactions created by the server don't have any message. The transactions the SDKs create have empty messages (when a message is not provided)

![image](https://user-images.githubusercontent.com/5390558/93948595-3eebc200-fd15-11ea-9961-29de7ce710e5.png)

![image](https://user-images.githubusercontent.com/5390558/93948602-414e1c00-fd15-11ea-84c2-89fb5fb707b5.png)

As far as I can see, the message binary is not optional, it would be 0s if emtpy.

https://github.com/nemtech/catbuffer/blob/main/schemas/transfer/transfer.cats#L24

This could be a problem. Maybe the binary created by server trimmed out the last part of the byte array creating a different hash?

**Comment by Jaguar0625** [comment]
type is optional

**Comment by fboucquez** [comment]
This is a bug in the SDKs. Thanks!
